"""V23M baseline registry with explicit reproduction status."""

from __future__ import annotations


BASELINE_REGISTRY = {
    "B0_V18R2_CANDIDATE_B": "PRESERVED_SERIALIZED",
    "B1_PERSISTENCE_PROXY": "REPRODUCED_CAUSALLY",
    "B2_LIGHTGBM_TWEEDIE": "PRESERVED_SERIALIZED",
    "B3_LIGHTGBM_QUANTILE": "PRESERVED_SERIALIZED",
    "B4_SEMANTIC_LIGHTGBM_HYBRID": "PRESERVED_B2_MEAN_PLUS_B3_QUANTILES",
    "B5_LIGHTGBM_RECURRENCE_FEATURES": "REPRODUCED_IN_RECURRENCE_GATE_R2_LOGISTIC_NOT_LIGHTGBM",
    "B6_HURDLE_NB_LOGNORMAL": "STRUCTURAL_HEAD_IMPLEMENTED_NOT_STANDALONE_REPRODUCED",
    "B7_DEEP_RENEWAL": "NOT_REPRODUCED_WITH_REASON:INDEPENDENT_MXNET_IMPLEMENTATION_UNAVAILABLE",
    "B8_RMTPP": "NOT_REPRODUCED_WITH_REASON:INDEPENDENT_REFERENCE_PIPELINE_UNAVAILABLE",
    "B9_THP": "NOT_REPRODUCED_WITH_REASON:INDEPENDENT_REFERENCE_PIPELINE_UNAVAILABLE",
    "B10_V19_C_MASS_TPP": "PRESERVED_SERIALIZED_ACCEPTED_FALSE",
    "B11_ACQ_FLEX": "REPRODUCED_CUDA_FIVE_FOLD_THREE_SEED",
    "B12_RACQ_FLEX": "NOT_RUN_RECURRENCE_GATE_FAIL",
}
