"""Separate source-backed local voltage-control infrastructure scenario.

The original MESS/AIDC objective and 0.950--1.050 Planning band are retained.
Hardware is common to B0/B1/B2/B3 and is frozen before Actual evaluation.
"""
VERSION = 'V42_DSTATCOM_LOCAL_VOLTVAR_INFRASTRUCTURE_V1'
SCENARIO_SCHEMA = 'V42_DSTATCOM_PHYSICAL_SCENARIO_V1'
MANIFEST_SCHEMA = 'V42_DSTATCOM_SOURCE_MODEL_SHA_MANIFEST_V1'
PLANNING_VMIN = .950
PLANNING_VMAX = 1.050
ACTUAL_VMIN = .950
ACTUAL_VMAX = 1.050
ENGINEERING_RESERVE_FACTOR = 1.5
CANARY_ATTEMPT = 'B2_MAY01_DSTATCOM_V1'
CAPITAL_AND_INSTALLATION_COSTS_IN_RESEARCH_SCOPE = False
