"""Korean report and SHA256 seal. Never constructs or solves a model."""
from run_hamming48 import *

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--pr-url',default='Draft PR 생성 후 기록');args=parser.parse_args()
    r=read(OUT/'RESULT.json');g=read(OUT/'GAP_UPDATE.json');diff=read(OUT/'TRAJECTORY_DIFF.json');grid=read(OUT/'GRID_EFFECT_AUDIT.json');comparison=read(OUT/'UB_COMPARISON.json');full=read(OUT/'BEST_FULL_REPLAY.json');phy=read(OUT/'BEST_CANDIDATE_PHYSICAL_REPLAY.json');raw=read(OUT/'BEST_CANDIDATE_FULL_REPLAY.json');start=read(OUT/'MIP_START_VALIDATION.json');next_action=read(OUT/'NEXT_ACTION_RECOMMENDATION.json');params=read(OUT/'SOLVER_PARAMETERS.json');center=read(OUT/'CENTER_VALIDATION.json')
    native_status={2:'OPTIMAL (restricted model, native MIPGap policy)',9:'TIME_LIMIT'}.get(r['Status'],str(r['Status']))
    text=f"# M1 Hamming48 / 600초 최종 검토\n\n{r['classification']}. 유효 UB {UB} → {r['UB_new']}; 추가 감소 {g['absolute_improvement']}. 기존 global LB {LB} 유지, 새 global gap {g['gap_new_percent']:.9f}%.\n\n"
    text+='| 필수 결과 | 값 |\n|---|---|\n'
    metrics=[('Old valid UB',g['UB_old']),('New valid UB',g['UB_new']),('Absolute improvement',g['absolute_improvement']),('Relative improvement',f"{g['relative_UB_improvement']} ({100*g['relative_UB_improvement']:.9f}%)"),('Global gap',f"{g['gap_new']} ({g['gap_new_percent']:.9f}%)"),('Native Runtime(s)',r['Runtime']),('Native Work',r['Work']),('Native nodes',r['NodeCount']),('Native status',f"{r['Status']} / {native_status}"),('Restricted ObjBound',r['neighborhood_ObjBound']),('Restricted native MIPGap',r['neighborhood_MIPGap']),('Improving incumbents (initial 제외)',r['number_of_improving_incumbents']),('MIPSOL events (초기/중복 포함)',r['MIPSOL_events']),('Native solution pool count',r['SolCount']),('Best valid-point Hamming',r['H_best']),('Radius48 boundary active',r['HAMMING_BOUNDARY_ACTIVE']),('Best solver candidate full replay',raw['PASS']),('Best valid point full replay',full['PASS']),('Changed node_activity B',diff['node_activity_bits_changed']),('Changed charge_mode B',diff['charge_mode_bits_changed']),('Changed discrete MESS',', '.join(diff['affected_discrete_units']) or '없음'),('Changed discrete slots',diff['affected_discrete_slots']),('Optimize calls',r['optimize_calls'])]
    for key,value in metrics:text+=f'| {key} | {value} |\n'
    text+='\n| 탐색 | Center UB | 반경 | Native Runtime(s) | Best valid UB | 개선 |\n|---|---:|---:|---:|---:|---:|\n'
    for label in ('Hamming24','Hamming48_300','Hamming48_600'):
        v=comparison[label];text+=f"| {label} | {v['center_UB']} | {v['radius']} | {v['Runtime']} | {v['best_valid_UB']} | {v['absolute_improvement']} |\n"
    text+=f"\n이번 gain / 직전300초 gain = {comparison['gain_600_over_gain_300']}. 진단: {comparison['diagnostic']}. 각각 새 검증 incumbent로 center를 갱신했으므로 순수한 TimeLimit 인과 비교는 아니다. 실패 또는 작은 개선은 전역 최적성/포화 증명이 아니다. 남은 UB−LB={g['remaining_separation']}도 증명된 integrality gap이라고 부르지 않는다.\n\n"
    text+=f"같은600초 실행에서 native_Runtime≤300에 저장된 최선 후보를 별도 original replay로 확인한 checkpoint valid UB={comparison['same_600s_run_verified_300s_checkpoint']}. 그 뒤 얻은 추가 valid gain={comparison['additional_valid_gain_after_300_seconds']}. 이는 같은 실행의 저장 point 비교이며, 다른600s-run 또는300s로 중단했을 경우의 반사실 solver 결과와 같다고 주장하지 않는다. 추가 optimize0회.\n\n"
    text+=f"Exact base HEAD는 `{BASE}`(PR170), scientific authority는 PR162 selected C3A `1d922c91eb27056a5ccc79c92ef18146707099ab`이다. 실행 사전등록 source commit은 `{read(OUT/'OPTIMIZE_ONCE.json')['source_commit']}`. 중심은 PR170 `docs/v42_m1_hamming48_20261007/BEST_VALID_POINT.npz`의 x, rho={UB}, SHA256={center['point_SHA256']}. Center original C3A/full physical/grid/A1 replay={center['PASS']}; start 제한 model replay={start['PASS']}, H=0, Start 배열 bit-identical, native start 수락={start['start_accepted']}. Center나 start 수리0.\n\n"
    text+='실제 PR170 실행 source와 저장 restriction을 읽어 free indices/names/순서가 같음을 확인했다. 2100 B=node_activity2016+charge_mode84, MESS01..04, slots64..84, radius48. 밖의 원래7222 B는 새 center로 고정한다. 원래296718 continuous bounds와582808 original rows/objective를 유지하고 Hamming row 하나만 덧붙였다. `sum(center=0: x)+sum(center=1:1−x)≤48`이며 continuous 변수는 Hamming에 세지 않는다.\n\n'
    text+=f"설정: {params['settings']}. PR170의 모든 effective native params를 비교했고 algorithm 변경은 TimeLimit300→600뿐이다. LogFile 경로는 새 namespace로 변경했다. Thread1, solver13.0.2. Native Runtime은 실제값을 그대로 기록했으며600초로 잘라 쓰지 않았다. Parameters는 solve 전후 동일하다.\n\n"
    text+=f"Native optimize={r['optimize_calls']}회. Exclusive ONCE token와 guard, 별도 presolve call0, sweep0, 더 큰 radius0, full global B&B0, 추가 수동 LB cut/hull0, formulation/physics/objective/tolerance 변경0. 모든 MIPSOL full C3A point·UTC·discovery wall/native time·Work·rho·Hamming·nodes·restricted bound/gap를 저장했다. 최초 center와 종료시 중복 event를 포함한 event 수와 native pool 수는 정의가 다르다. Native callback 오류={r['callback_errors']}, solver exception={r['solver_exception']}.\n\n"
    if 'original_C3A' in raw:
        v=raw['original_C3A'];text+=f"최선 solver 후보 C3A replay: PASS={v['PASS']}, 행 최대위반={v['max_constraint_violation']}, bounds 최대위반={v['max_bound_violation']}, B integrality 최대위반={v['max_integrality_violation']}. 전체306040 C3A vector를 저장한 뒤 frozen saved inverse로 원래 physical vector를 복원했다.\n\n"
    physical=phy['original_physical_audit'];grid_replay=physical['exhaustive_grid'];physics=physical.get('route_SOC_PCS',{})
    text+=f"원래 physical replay={phy['PASS']}, grid replay={grid_replay['PASS']}, grid checked rows={grid_replay['checked_rows']}, grid maximum upper={grid_replay['maximum_upper']}. Route/SOC/PCS replay={physics.get('PASS')}, exact circle maximum ratio={physics.get('max_exact_circle_ratio')}, movement energy={physics.get('mobility_energy_kwh')} kWh. Frozen A1 DATA/identity hashes를 동일 reader로 확인했다. 원래 B 밖의 고정값은 모두 유지했으며 saved inverse route auxiliary 차이={phy['route_auxiliary_inverse_max_difference']}. C3 raw vector를 수정하거나 candidate 수리를 하지 않았다. Native/C3 tolerance1e−8, 기존 full affine inverse tolerance1e−6, bound/route/grid1e−8, 기존 physical subvalidator1e−5 모두 유지했다.\n\n"
    text+=f"최선 native 후보가 FAIL이면 그 점은 UB로 배제하고 저장된 다른 improving 점을 objective 순으로 검증한다. 채택 valid point SHA256={full['best_valid_point_SHA256']}. 후보 검증 이력은 CANDIDATE_VALIDATION_HISTORY.json에 있다. Valid improvement가 없으면 baseline UB를 유지한다. 이번 valid full replay={full['PASS']}. Global LB를 변경하지 않았고 restricted ObjBound={r['neighborhood_ObjBound']}를 global LB로 사용하지 않았다.\n\n"
    totals=diff['totals'];text+=f"Discrete 변경 unit={diff['affected_discrete_units']}, slots={diff['affected_discrete_slots']}. 원래 outside B 변경0. 물리 continuous 변경 unit={diff['affected_physical_continuous_units']}, slots={diff['affected_physical_continuous_slots']}. STAY 결정 변경={diff['STAY_decisions_changed']}, MOVE 결정 변경={diff['MOVE_decisions_changed']}; MOVE 개수 {totals['MOVE_count']['old']}→{totals['MOVE_count']['new']}, movement kWh {totals['movement_energy_kwh']['old']}→{totals['movement_energy_kwh']['new']}. 원래 route auxiliary의 depart/connect 시각은 binary label 시간과 다를 수 있으며 neighborhood B를 추가로 연 것은 아니다.\n\n"
    text+=f"충전 활성 event {totals['charge_events']['old']}→{totals['charge_events']['new']}, 방전 {totals['discharge_events']['old']}→{totals['discharge_events']['new']}; 활성여부 변경 충전{diff['charging_events_changed']}/방전{diff['discharging_events_changed']}개(진단 threshold1e−8 kW). 충전 energy {totals['charge_energy_kwh']['old']}→{totals['charge_energy_kwh']['new']} kWh, 방전 {totals['discharge_energy_kwh']['old']}→{totals['discharge_energy_kwh']['new']} kWh. 모든 unit·96 slots Pch/Pdis/Q/SOC와 시작/말기 SOC, route changes는 TRAJECTORY_DIFF.json 및 시간 CSV에 기록했다.\n\n"
    text+=f"원래 retained thermal rows {grid['all_retained_thermal_rows_evaluated']}개를 모두 평가했다. Center-active 개선 상위100, 전체 개선 상위100, center/new 요구rho 각각 상위100 및 PR169 critical descriptors를 합친 {grid['selected_rows']}개 row를 CSV에 기록했다. 실제 native branch/time은 frozen row axes로 복구했다.\n\n| Center critical grid row | Slot | C3A row | 요구 rho 감소 |\n|---|---:|---:|---:|\n"
    for v in grid['largest_critical_row_improvements'][:6]:text+=f"| {v['branch_name']} | {v['slot']} | {v['C3A_row']} | {v['required_rho_reduction']} |\n"
    text+='\n| Slots64..84 내 critical grid row | Slot | C3A row | 요구 rho 감소 |\n|---|---:|---:|---:|\n'
    for v in grid['largest_critical_row_improvements_in_binary_block'][:6]:text+=f"| {v['branch_name']} | {v['slot']} | {v['C3A_row']} | {v['required_rho_reduction']} |\n"
    text+='\nPch/Pdis/Q의 affine 기여와 grid 개선은 동반 관찰이며 인과 분해가 아니다. 원래 continuous 변수 전체가 자유로우므로 discrete 시간 block 밖의 grid 변화도 가능하다.\n\n'
    text+=f"다음 행동은 정확히1개: **{next_action['recommendation']}** 이유: {next_action['rationale']} 실행={next_action['executed']}. 이 작업은 여기서 끝나며 다른 solve는 수행하지 않는다.\n\n"
    text+=f"Draft PR: {args.pr_url}\n\n최종40자리 HEAD는 Draft PR 본문의 `Final HEAD`와 사용자 최종 응답에 기록한다. `git rev-parse HEAD`로 확인한다. 동일 commit 파일에 자체 SHA를 넣는 순환을 만들지 않는다. Manifest는 자기 자신과 Python cache를 제외한 namespace 전체 파일의 원본 bytes를 SHA256으로 봉인한다. PR169/170 및 scientific 자료는 기존 hashes와 같아야 하며 최종 작업 트리는 clean이어야 한다.\n"
    (OUT/'FINAL_REVIEW_KO.md').write_text(text,encoding='utf-8')
    verification=read(OUT/'VERIFICATION.json');verification.update(Draft_PR_URL=args.pr_url,manifest_excludes_itself=True,final_HEAD_authority='Published Draft PR body Final HEAD; git rev-parse HEAD; final user response');write('VERIFICATION.json',verification)
    files={str(p.relative_to(OUT)).replace('\\','/'):sha(p) for p in sorted(OUT.rglob('*')) if p.is_file() and p.name!='SHA256_MANIFEST.json' and '__pycache__' not in str(p) and p.suffix!='.pyc'}
    write('SHA256_MANIFEST.json',dict(algorithm='SHA256',scope='All namespace files except manifest itself and Python caches',files=files))
    print('SEALED',len(files),flush=True)
if __name__=='__main__':main()
