"""Frozen scientific and filesystem contracts for V35R3F.

The source root is external and read-only by design. It may be overridden for
testing with ``DATASET312_AUTHORITY_ROOT``; the production default is the
authority path named in the task contract.
"""

from __future__ import annotations

import os
from pathlib import Path


PARENT_HEAD = "9034dd40f89a2d226a9bbbd47548224998ee3564"
BRANCH = "codex/v35r3f-dataset312-h100-power-authority"
DATASET_ID = 312
DATASET_VERSION = 2
DATASET_DOI = "10.7799/3025227"
ARCHIVE_SHA256 = "dcad6de800fb565d850b163902e2eddae48aabd1ed1c7336f9a1cdaf3012f137"
ARCHIVE_BYTES = 1_070_866_623

DEFAULT_AUTHORITY_ROOT = Path(
    r"C:\Users\kjw39\OneDrive\Desktop\4-2\Mobile ESS\raw데이터\데이터 센터\NLR_scheduler_authority"
)
AUTHORITY_ROOT = Path(os.environ.get("DATASET312_AUTHORITY_ROOT", DEFAULT_AUTHORITY_ROOT))
DATASET_ROOT = AUTHORITY_ROOT / "08_NLR_Kestrel_H100_GenAI_Power_Dataset312"
ARCHIVE = DATASET_ROOT / "dataset312_v2_dataset.zip"
EXTRACTED_ROOT = DATASET_ROOT / "dataset_v2"
MANIFEST_ROOT = AUTHORITY_ROOT / "99_manifest" / "dataset312_h100_power"

ARTIFACT_DIRNAME = "v35r3f_dataset312_h100_power_authority"
CACHE_DIRNAME = ARTIFACT_DIRNAME
LOG_DIRNAME = ARTIFACT_DIRNAME

GPU_FIELDS_MW = tuple(f"gpu-{index}[mW]" for index in range(4))
GPU_TEMP_FIELDS_C = tuple(f"gpu-{index}[C]" for index in range(4))
RAPL_PACKAGE_FIELDS_W = ("cpu-0[W]", "cpu-1[W]")
RAPL_CORE_FIELDS_W = ("cpu-0-core[W]", "cpu-1-core[W]")

# This is a component sum, not a whole-node AC/DC input measurement. Package
# domains are used once; nested core domains are deliberately not added again.
PRIMARY_BOUNDARY = "GPU_PLUS_RAPL_PACKAGE_COMPONENT_SUM"
SECONDARY_BOUNDARIES = (
    "GPU_ONLY_POWER",
    "RAPL_PACKAGE_POWER",
    "RAPL_CORE_SUBDOMAIN_POWER",
    "DATASET_PROVIDED_GPU_PLUS_RAPL_PACKAGE_PLUS_CORE_SUM",
)

RAW_AGGREGATE_MEAN_RTOL = 5e-4
RAW_AGGREGATE_ENERGY_RTOL = 5e-3
RAW_AGGREGATE_QUANTILE_RTOL = 2e-2
SENSOR_LIMIT_W = 800.0
GAP_FACTOR = 1.5
GPUS_PER_NODE = 4

RESOURCE_STATE_SUPPORT = "STATE_SUPPORT_FULL_NODE_EXCLUSIVE_ONLY"
POWER_AUTHORITY_LEVEL = "H1_COMPONENT_LEVEL_H100_POWER_AUTHORITY"
PRIMARY_CLASSIFICATION = "V35R3F_DATASET312_COMPONENT_ONLY"
PARTIAL_SHARED_ANSWER = "NO_DEFENSIBLE_PUBLIC_BRIDGE"
KESTREL_NODE_PACKING_NEXT = "DEFER"

FORBIDDEN_ASSERTIONS = {
    "DATASET312_TO_KESTREL_JOB_DIRECT_JOIN": "FORBIDDEN",
    "RADDIT_CPU_POWER_USED_FOR_H100_MAGNITUDE": "NO",
    "PRODUCTION_INTEGRATION_RECOMMENDED": "NO",
}

REQUIRED_ARTIFACTS = (
    "V35R3F_START_STATE.json",
    "V35R3F_ISOLATION_AUDIT.json",
    "V35R3F_SOURCE_AUTHORITY.json",
    "V35R3F_DATASET312_ARCHIVE_INVENTORY.csv",
    "V35R3F_DATASET312_ARCHIVE_INVENTORY.json",
    "V35R3F_DATASET312_SCHEMA_CENSUS.json",
    "V35R3F_POWER_SENSOR_SEMANTICS.json",
    "V35R3F_TIMEBASE_AUDIT.csv",
    "V35R3F_EXPERIMENT_CENSUS.parquet",
    "V35R3F_EXPERIMENT_DIMENSIONS.json",
    "V35R3F_RESOURCE_STATE_SUPPORT.json",
    "V35R3F_RAW_PROFILE_STATISTICS.parquet",
    "V35R3F_TRANSIENT_STEADY_STATE_AUDIT.json",
    "V35R3F_RAW_AGGREGATED_RECONCILIATION.csv",
    "V35R3F_RAW_AGGREGATED_RECONCILIATION.json",
    "V35R3F_NODE_SCALING.parquet",
    "V35R3F_NODE_SCALING_SUMMARY.json",
    "V35R3F_WORKLOAD_POWER_VARIABILITY.parquet",
    "V35R3F_WORKLOAD_POWER_VARIABILITY.json",
    "V35R3F_CLASS_AGNOSTIC_POWER_ENVELOPE.parquet",
    "V35R3F_POWER_ENVELOPE_CONTRACT.json",
    "V35R3F_MEASUREMENT_BOUNDARY_AUTHORITY.json",
    "V35R3F_ENERGY_INTEGRATION_AUDIT.json",
    "V35R3F_DATA_QUALITY_AUDIT.csv",
    "V35R3F_EXCLUSION_MANIFEST.json",
    "V35R3F_KESTREL_BRIDGE_ELIGIBILITY_MATRIX.json",
    "V35R3F_NEXT_NODE_PACKING_CONTRACT.json",
    "V35R3F_POWER_AUTHORITY_DECISION.json",
    "V35R3F_REPAIR_LOG.json",
    "V35R3F_COMPUTE_ACCOUNTING.json",
    "V35R3F_TEST_REPORT.json",
    "V35R3F_FINAL_REVIEW.json",
    "V35R3F_FINAL_REVIEW.md",
)
