import sys,csv,json
from pathlib import Path
from datetime import datetime,timezone
import numpy as np
sys.dont_write_bytecode=True
import stress_common as s
H=s.H
def main():
    s.check_freeze();rule=s.read(H/'STRESS_CALIBRATION_RULE.json');rows=s.read(H/'STRESS_CALIBRATION_SCREEN_TABLE.json');selection=s.read(H/'PROVISIONAL_STRESS_SELECTION.json');replay=s.read(H/'INDEPENDENT_REPLAY_VERIFICATION.json')
    assert [(r['source_pu'],r['vreg_V'],r['alpha']) for r in rows]==[(v,g,a) for v in rule['source_grid'] for g in rule['all_regulator_Vreg_grid_V'] for a in rule['alpha_grid']]
    validated=[];overlap=[]
    for r in rows:
        folder=s.case_folder(r['source_pu'],r['vreg_V'],r['alpha']);assert s.read(folder/'PRE_SOLVE_ALLOWED_CHANGE_AUDIT.json')['status']=='PASS' and s.read(folder/'STATIC_CONSERVATION_AUDIT.json')['status']=='PASS'
        states=s.read(folder/'B0_CONTROL_STATES_96.json');assert len(states)==96
        for state in states:
            assert state['source_pu']==r['source_pu'] and len(state['regulators'])==12 and len(state['capacitors'])==10 and len(state['capcontrols'])==9
            assert all(c['Vreg']==r['vreg_V'] and c['band']==2 and c['PT_ratio']==60 and c['enabled'] for c in state['regulators'])
            assert all(c['enabled']==(c['name']!='capbank3') for c in state['capacitors']) and all(c['enabled'] for c in state['capcontrols'])
        with np.load(folder/'B0_ALL_PHASE_ARRAYS.npz') as z:
            arrays=[z[k] for k in s.KEYS];assert arrays[0].shape==(96,8639) and all(x.shape[0]==96 and np.isfinite(x).all() for x in arrays)
            feasible=r['converged_slots']==96 and r['control_complete_slots']==96 and r['solver_error_slots']==0 and arrays[0].min()>=.95-1e-9 and arrays[0].max()<=1.05+1e-9 and all(x.max()<=1+1e-9 for x in arrays[1:]);assert bool(feasible)==r['feasible']
            computed=dict(Vmin_pu=float(arrays[0].min()),Vmax_pu=float(arrays[0].max()),max_phase_line_loading_pu=float(arrays[1].max()),max_transformer_phase_current_pu=float(arrays[2].max()),max_transformer_winding_kva_pu=float(arrays[3].max()));assert all(computed[k]==r[k] for k in computed)
        assert r['target_absolute_error_pu']==abs(r['max_phase_line_loading_pu']-.85) and r['lexicographic_key']==list(s.ranking_key(r))
        validated.append(dict(source_pu=r['source_pu'],vreg_V=r['vreg_V'],alpha=r['alpha'],status='PASS',feasible=bool(feasible)))
        if (folder/'PREVIOUS_125V_CASE_REPRODUCTION.json').exists():
            check=s.read(folder/'PREVIOUS_125V_CASE_REPRODUCTION.json');assert check['status']=='PASS';overlap.append(dict(source_pu=r['source_pu'],alpha=r['alpha'],**check))
    assert len(overlap)==15
    ranked=sorted([r for r in rows if r['feasible']],key=lambda r:(abs(r['max_phase_line_loading_pu']-.85),abs(r['vreg_V']-125.),abs(r['source_pu']-1.05),-r['alpha']));chosen=ranked[0] if ranked else None;assert chosen==selection['selected']
    accepted=chosen is not None and replay['status']=='PASS'
    status='IEEE8500_STRESS_CALIBRATED_B0_AUTHORITY' if accepted else ('INDEPENDENT_REPLAY_FAILED_NO_STRESS_AUTHORITY' if chosen else 'NO_FEASIBLE_CASE_ON_FROZEN_STRESS_CALIBRATION_GRID')
    protected=s.read(H/'PROTECTED_AUTHORITIES_BEFORE.json');changed=[r['path'] for r in protected if s.record(Path(r['path']))!=r];assert not changed;s.check_freeze()
    s.save(H/'GRID_VALIDATION.json',dict(status='PASS',cases=validated,saved_phase_array_extrema_and_feasibility_recomputed=True,lexicographic_ranking_independently_recomputed=True,overlap_cases_reproduced=overlap,total_screen_slots=9600))
    s.save(H/'IMMUTABILITY_FINAL_AUDIT.json',dict(status='PASS',protected_files=len(protected),SHA256_size_mtime_unchanged=True,changed_files=changed,pre_execution_bindings_unchanged=True,prior_voltage_feasible_authority_unchanged=True))
    authority=dict(status=status,final_authority_valid=accepted,source_pu=chosen['source_pu'] if accepted else None,all_regulator_Vreg_V=chosen['vreg_V'] if accepted else None,alpha8500=chosen['alpha'] if accepted else None,target_max_phase_line_loading_pu=.85,target_interpretation=rule['target_interpretation'],selected_date='2025-05-21',selection_rule=rule['selection_rule'],selected_summary=chosen if accepted else None,lexicographic_rank=1 if accepted else None,feasible_case_count=len(ranked),canonical_IEEE8500_reproduction=False,prior_voltage_feasible_compatibility_authority=s.read(H/'PRESERVED_VOLTAGE_FEASIBLE_AUTHORITY.json'),rule_sha256=s.sha(H/'STRESS_CALIBRATION_RULE.json'),pre_execution_manifest_sha256=s.sha(H/'PRE_EXECUTION_FREEZE_MANIFEST.json'),independent_replay_verification_sha256=s.sha(H/'INDEPENDENT_REPLAY_VERIFICATION.json'),screen_cases=100,screen_slots=9600,independent_replay_slots=replay['simulation_slots'],unchanged_physical_limits=rule['limits'],B1_B2_B3_reads_or_runs=0,additional_tuning=0)
    if accepted:
        authority['selected_overlay']=s.record(s.overlay_path(chosen['source_pu'],chosen['vreg_V']));authority['selected_phase_arrays']=s.record(s.case_folder(chosen['source_pu'],chosen['vreg_V'],chosen['alpha'])/'B0_ALL_PHASE_ARRAYS.npz')
        s.save(H/'IEEE8500_STRESS_CALIBRATED_B0_AUTHORITY.json',authority)
        with (s.case_folder(chosen['source_pu'],chosen['vreg_V'],chosen['alpha'])/'B0_96_SLOT_EXTREMA.csv').open(encoding='utf-8',newline='') as f:selected_rows=list(csv.DictReader(f))
        witnesses={k:(min if k=='Vmin_pu' else max)(selected_rows,key=lambda r:float(r[k])) for k in ['Vmin_pu','Vmax_pu','max_phase_line_loading_pu','max_transformer_phase_current_pu','max_transformer_winding_kva_pu']};s.save(H/'SELECTED_GLOBAL_EXTREMA_WITNESSES.json',witnesses)
        overlay=s.overlay_path(chosen['source_pu'],chosen['vreg_V']);(H/'Master_IEEE8500_STRESS_CALIBRATED_B0.dss').write_text(f'! Frozen stress-calibrated study model, not canonical IEEE8500 reproduction.\nCompile "{s.PCC / "Master_IEEE8500_PCC.dss"}"\nRedirect "{overlay}"\nRedirect "{s.OLD / "B0_RESOURCE_OBJECTS.dss"}"\n! No Solve: use the frozen chronological input procedure and alpha={chosen["alpha"]:.2f}.\n',encoding='utf-8')
    s.save(H/'STRESS_CALIBRATION_OUTCOME.json',authority)
    groups=[]
    for source in rule['source_grid']:
        for vreg in rule['all_regulator_Vreg_grid_V']:
            subset=[r for r in rows if r['source_pu']==source and r['vreg_V']==vreg];good=sorted([r for r in subset if r['feasible']],key=s.ranking_key);groups.append(dict(source_pu=source,vreg_V=vreg,feasible_alphas=[r['alpha'] for r in subset if r['feasible']],closest_feasible_alpha=good[0]['alpha'] if good else None,closest_line_loading_pu=good[0]['max_phase_line_loading_pu'] if good else None,converged_slots=sum(r['converged_slots'] for r in subset),control_complete_slots=sum(r['control_complete_slots'] for r in subset)))
    s.table(H/'STRESS_GRID_SUMMARY.csv',groups)
    report=['# IEEE8500 B0-only stress calibration','',f'**{status}**','',f'Final source pu = **{authority["source_pu"]}**, all-regulator Vreg = **{authority["all_regulator_Vreg_V"]} V**, alpha8500 = **{authority["alpha8500"]}**.','', 'The original **(source pu=1.045, alpha8500=0.25)** evidence and authority remain unchanged as the voltage-feasible compatibility authority. This new artifact is a separate stress-calibrated B0 authority. It is a reduced-load study adaptation, **not canonical IEEE8500 reproduction**.','', 'The fixed target **0.85 pu maximum phase-line loading** was defined before execution as a stressed-but-feasible large-feeder baseline, not as an instruction to reproduce an IEEE123 result. All **100 combinations / 9,600 chronological B0 AC slots** were freshly evaluated. Source grid: 1.0450, 1.0425, 1.0400, 1.0375, 1.0350; common Vreg grid: 125.0, 124.5, 124.0, 123.5 V; alpha grid: 0.40, 0.45, 0.50, 0.55, 0.60.','', 'Selection first discards every case with any physical, convergence or control-settling failure. It then minimizes the unrounded lexicographic key **(|line maximum−0.85|, |Vreg−125|, |source−1.05|, −alpha)**. No grid refinement or post-result tuning is performed.','', 'Hard limits remain 0.95–1.05 pu voltage at all 8639 nodes and loading ≤1.0 pu for both active line terminals, transformer phase currents and every transformer winding apparent power. The prior numerical boundary tolerance 1e-9 is unchanged. Each case starts with a fresh engine and carries accepted tap/cap states through 96 sequential slots; MaxIterations=100 and MaxControlIterations=1000 remain unchanged. Five isolated source processes have no shared control state.','', 'Native topology, impedance, original line/transformer ratings, 12 AIDC PCCs and 24 MESS service PCCs across 24 service locations, and AIDC/MESS power/energy/GPU scales are unchanged. Selected date 2025-05-21, causal D-1 demand/PV temporal inputs, native P/Q/PF and proportional PV phase allocation are preserved. Controlled capacitors/CapControls, PT ratio=60, band=2 V and tap limits are unchanged; CAPBank3 stays OFF. No Actual, B1/B2/B3, sensitivity or optimization performance input is used.','']
    if accepted:
        report.extend([f'**{len(ranked)} / 100 cases are feasible.** Selected target error: **{chosen["target_absolute_error_pu"]:.12f} pu**.','', '| Quantity | Screening | Clean independent replay |','|:---|---:|---:|'])
        for k in ['Vmin_pu','Vmax_pu','max_phase_line_loading_pu','max_transformer_phase_current_pu','max_transformer_winding_kva_pu']:report.append(f'| {k} | {chosen[k]:.12f} | {replay["summary"][k]:.12f} |')
        report.extend(['',f'Independent replay **PASS**, 96/96 slots: separate clean process/context, scalar bus and element measurement APIs, matching accepted tap/cap states, and no unexpected static drift. Maximum phase-array difference is {max(replay["max_absolute_phase_array_differences"].values()):.3g} pu.','', 'Top feasible cases under the frozen ranking:','', '| rank | source | Vreg | alpha | line max | target error |','|---:|---:|---:|---:|---:|---:|'])
        for i,r in enumerate(ranked[:10]):report.append(f'| {i+1} | {r["source_pu"]:.4f} | {r["vreg_V"]:.1f} | {r["alpha"]:.2f} | {r["max_phase_line_loading_pu"]:.12f} | {r["target_absolute_error_pu"]:.12f} |')
    else:report.extend(['No stress-calibrated authority is accepted. Stop without additional tuning. Independent replay status: **'+replay['status']+'**.'])
    report.extend(['',f'All **{len(protected)} prior evidence files** retain SHA256, size and modification time, including the prior voltage-feasible authority. Pre-execution rule/code/input bindings are unchanged. The 15 overlapping 125-V cases reproduce the previous frozen phase arrays within 1e-10 pu.','', 'B1/B2/B3 reads or executions: **0**. Tuning outside the frozen grid: **0**.','', 'Artifacts: STRESS_CALIBRATION_SCREEN_TABLE.csv (100 cases), B0_9600_SLOT_EXTREMA.csv, RANKED_FEASIBLE_CASES.csv, per-case phase arrays/control states/static audits, independent replay, selected global witnesses, authority, preserved-previous-authority record, and pre-execution/final SHA manifests.','', '', '## All 100 cases','', '| source | Vreg | alpha | feasible | conv/settled | Vmin | Vmax | line I | transformer I | transformer kVA |','|---:|---:|---:|:---:|:---:|---:|---:|---:|---:|---:|'])
    for r in rows:report.append(f'| {r["source_pu"]:.4f} | {r["vreg_V"]:.1f} | {r["alpha"]:.2f} | {r["feasible"]} | {r["converged_slots"]}/{r["control_complete_slots"]} | {r["Vmin_pu"]:.9f} | {r["Vmax_pu"]:.9f} | {r["max_phase_line_loading_pu"]:.9f} | {r["max_transformer_phase_current_pu"]:.9f} | {r["max_transformer_winding_kva_pu"]:.9f} |')
    (H/'IEEE8500_STRESS_CALIBRATION_REPORT.md').write_text('\n'.join(report)+'\n',encoding='utf-8')
    mf=H/'STRESS_CALIBRATION_EVIDENCE_FREEZE_MANIFEST.json';assert not mf.exists();files=[dict(path=str(p.relative_to(H)),sha256=s.sha(p),bytes=p.stat().st_size) for p in sorted(H.rglob('*')) if p.is_file() and p.name not in [mf.name,'STRESS_CALIBRATION_EVIDENCE_FREEZE_MANIFEST.sha256']]
    s.save(mf,dict(frozen_at_utc=datetime.now(timezone.utc).isoformat(),status=status,source_pu=authority['source_pu'],all_regulator_Vreg_V=authority['all_regulator_Vreg_V'],alpha8500=authority['alpha8500'],target_line_loading=.85,pre_execution_manifest_sha256=s.sha(H/'PRE_EXECUTION_FREEZE_MANIFEST.json'),protected_files_unchanged=len(protected),B0_screen_slots=9600,independent_replay_slots=replay['simulation_slots'],independent_replay_status=replay['status'],B1_B2_B3_reads_or_runs=0,files=files));(H/'STRESS_CALIBRATION_EVIDENCE_FREEZE_MANIFEST.sha256').write_text(s.sha(mf)+'  '+mf.name+'\n',encoding='ascii');print('FINAL_STRESS_FREEZE_COMPLETE',status,authority['source_pu'],authority['all_regulator_Vreg_V'],authority['alpha8500'],s.sha(mf),flush=True)
if __name__=='__main__':main()
