import subprocess
from .common import *
def main():
    OUT.mkdir(parents=True,exist_ok=True);LOCAL.mkdir(parents=True,exist_ok=True)
    files=subprocess.check_output(['git','ls-tree','-r','--name-only',BASE],cwd=ROOT,text=True).splitlines()
    dump('LEGACY_PRESERVATION_AUDIT.json',dict(base=BASE,files=[dict(path=p,sha256=sha(ROOT/p)) for p in files],PASS=True,scope='exact-base checkout bytes; inherited Git text conversion remains unchanged'))
    prior=read(ROOT/'docs/v42_exact_wan_factorized_milp/MAY_SELECTED_MODEL_STATS.json')
    dump('PR102_BASELINE_RECEIPT.json',dict(base=BASE,PR102_BASE_PRESERVED=True,model=prior,presolved=dict(rows=7533647,columns=7247816,nonzeros=46376330),root=dict(objective=0.6716023396111563,iterations=457124,seconds=1557.90),optimization=read(ROOT/'docs/v42_exact_wan_factorized_milp/MAY_A1_OPTIMIZATION.json')))
    dump('PREREGISTRATION.json',dict(base=BASE,production='one complete physical joint MILP',candidates=['F2','F2A','F2B','F2C'],solver=dict(Seed=20260929,Threads=1,MIPGap=.005,TimeLimit=3600),scientific_levels=['rho','reserve_shortfall','CC4_reference_deviation','migration_count','shift_slots','prestart_changes'],tie_policy=dict(F2='original rank tie retained for baseline diagnosis, only six scientific levels in diagnostics',successors='remove non-scientific rank rows; deterministic UID and physical signature postprocessing; all six scientific levels preserved'),selection=dict(priority=['lowest completed optimal P1 LP diagnostic wall','if within 5% prefer stronger lower bound','within 1e-7 bound prefer fewer nonzeros','rows plus columns','F2,F2A,F2B,F2C simplicity order'],root_wall_close_relative=.05,root_bound_close_absolute=1e-7,incomplete_LP_diagnostic='not selected unless no completed eligible candidate; fallback unchanged F2',MIP_objectives_used=False),LP_diagnostic=dict(TimeLimit=3600,Threads=1,Seed=20260929,numerical_settings='inherited defaults, no sweep',scope='continuous relaxation P1 only; separate from production budget'),MIP_start=dict(order=['source-backed current validated reference/native plan','earlier exact same-authority plan','deterministic reference no-migration if full global validation passes'],partial='clearly labeled optional hint; never called incumbent',feasibility_attempt='at most one exact same-full-feasible-set zero-objective attempt, 600 seconds, no slack, only if source-backed plan fails; separately timed'),production_A1=dict(exactly_one=True,optimize_only_seconds=3600,build_validation_excluded=True,includes=['presolve','root','cuts','heuristics','B&B'],return_publication_grace_seconds=5,lex='inherited locks after OPTIMAL status only, cumulative optimize budget'),state_elimination='algebraic projection only; reject dense cumulative expansions without measured LP benefit',aggregation='only with exact individual decomposability; fail closed on coupled service/WAN mixing; do not force F2C',bounded_tolerances=dict(FeasibilityTol=1e-9,OptimalityTol=1e-9,IntFeasTol=1e-9,MIPGap=0,TimeLimit_per_level=90,objective_absolute=3e-6,objective_relative=1e-7),no_scientific_change=True,no_decomposition=True,no_later_pipeline=True,created_utc=time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime())))
if __name__=='__main__':main()
