import sys,json
from pathlib import Path
from datetime import datetime,timezone
import numpy as np
sys.dont_write_bytecode=True
import screen_source_grid as s
H=s.H
def main():
    s.check_freeze();rule=s.read(H/'SOURCE_GRID_RULE.json');rows=s.read(H/'SOURCE_ALPHA_SCREEN_TABLE.json');sel=s.read(H/'PROVISIONAL_LEXICOGRAPHIC_SELECTION.json');replay=s.read(H/'INDEPENDENT_REPLAY_VERIFICATION.json')
    assert [(r['source_pu'],r['alpha']) for r in rows]==[(v,a) for v in rule['source_grid_descending'] for a in rule['alpha_grid_descending']]
    validation=[]
    for r in rows:
        folder=H/'screen'/f'source_{r["source_pu"]:.3f}'/f'alpha_{r["alpha"]:.2f}';assert s.read(folder/'STATIC_CONSERVATION_AUDIT.json')['status']=='PASS' and s.read(folder/'PRE_SOLVE_ALLOWED_CHANGE_AUDIT.json')['status']=='PASS'
        states=s.read(folder/'B0_CONTROL_STATES_96.json');assert len(states)==96
        assert all(x['source_pu']==r['source_pu'] and len(x['regulators'])==12 and len(x['capacitors'])==10 and len(x['capcontrols'])==9 for x in states)
        with np.load(folder/'B0_ALL_PHASE_ARRAYS.npz') as z:
            arrays=[z[k] for k in s.KEYS];assert arrays[0].shape==(96,8639) and all(x.shape[0]==96 and np.isfinite(x).all() for x in arrays)
            feasible=r['converged_slots']==96 and r['control_complete_slots']==96 and r['solver_error_slots']==0 and arrays[0].min()>=.95-1e-9 and arrays[0].max()<=1.05+1e-9 and all(x.max()<=1+1e-9 for x in arrays[1:]);assert bool(feasible)==r['feasible']
            computed=dict(Vmin_pu=float(arrays[0].min()),Vmax_pu=float(arrays[0].max()),max_phase_line_loading_pu=float(arrays[1].max()),max_transformer_phase_current_pu=float(arrays[2].max()),max_transformer_winding_kva_pu=float(arrays[3].max()));assert all(computed[k]==r[k] for k in computed)
        validation.append(dict(source_pu=r['source_pu'],alpha=r['alpha'],status='PASS',feasible=bool(feasible)))
    good=[r for r in rows if r['feasible']];chosen=max(good,key=lambda r:(r['source_pu'],r['alpha'])) if good else None;assert chosen==sel['selected']
    if chosen:
        accepted=replay['status']=='PASS';status='FINAL_SOURCE_ALPHA_OPERATING_POINT_AUTHORITY' if accepted else 'INDEPENDENT_REPLAY_FAILED_NO_FINAL_AUTHORITY'
    else:
        assert replay['status']=='NOT_APPLICABLE_NO_FEASIBLE_PAIR';accepted=False;status='NO_FEASIBLE_PAIR_ON_FROZEN_SOURCE_ALPHA_GRID'
    protected=s.read(H/'PROTECTED_AUTHORITIES_BEFORE.json');changed=[r['path'] for r in protected if s.record(Path(r['path']))!=r];assert not changed;s.check_freeze()
    s.save(H/'GRID_VALIDATION.json',dict(status='PASS',cases=validation,all_105_cases_recomputed_from_saved_phase_arrays=True,total_screen_slots=10080,all_source_1p050_cases_reproduced_previous_stage=True))
    s.save(H/'IMMUTABILITY_FINAL_AUDIT.json',dict(status='PASS',protected_files=len(protected),SHA256_size_mtime_unchanged=True,changed_files=changed,pre_execution_bindings_unchanged=True))
    authority=dict(status=status,final_authority_valid=accepted,source_pu=chosen['source_pu'] if accepted else None,alpha8500=chosen['alpha'] if accepted else None,selected_date=rule['selected_date'],selection_rule='Lexicographic maximum feasible (source_pu, alpha) over the exact 5 x 21 frozen grid; verified by a separate clean 96-slot replay',canonical_IEEE8500_reproduction=False,compatibility_adaptation_only=True,rule_sha256=s.sha(H/'SOURCE_GRID_RULE.json'),pre_execution_manifest_sha256=s.sha(H/'PRE_EXECUTION_FREEZE_MANIFEST.json'),independent_replay_sha256=s.sha(H/'INDEPENDENT_REPLAY_VERIFICATION.json'),selected_summary=chosen if accepted else None,feasible_pairs=len(good),screen_cases=105,screen_slots=10080,independent_replay_slots=replay['simulation_slots'],preserved_conditions='All regulator Vreg=125 V, PT ratio=60, band=2 V, original tap limits, CAPBank3 OFF, all nine controlled caps/CapControls unchanged; original topology/impedances/ratings/PCCs/24-location mapping/AIDC-MESS scales/hard limits unchanged',B1_B2_B3_runs=0,additional_tuning=0)
    if accepted:
        authority['selected_source_overlay']=s.record(H/f'Source_{chosen["source_pu"]:.3f}_Compatibility.dss');authority['selected_phase_arrays']=s.record(H/'screen'/f'source_{chosen["source_pu"]:.3f}'/f'alpha_{chosen["alpha"]:.2f}'/'B0_ALL_PHASE_ARRAYS.npz')
        selected_overlay=H/f'Source_{chosen["source_pu"]:.3f}_Compatibility.dss'
        (H/'Master_FINAL_IEEE8500_OperatingPoint.dss').write_text(f'! FINAL adapted study model, not canonical IEEE8500 reproduction.\nCompile "{s.PCC / "Master_IEEE8500_PCC.dss"}"\nRedirect "{selected_overlay}"\nRedirect "{s.OLD / "B0_RESOURCE_OBJECTS.dss"}"\n! No Solve: source={chosen["source_pu"]:.3f}, alpha={chosen["alpha"]:.2f}; apply frozen 96-slot inputs.\n',encoding='utf-8')
    s.save(H/'FINAL_OPERATING_POINT_AUTHORITY.json',authority)
    source_rows=[]
    for source in rule['source_grid_descending']:
        subset=[r for r in rows if r['source_pu']==source];feasible=[r['alpha'] for r in subset if r['feasible']];source_rows.append(dict(source_pu=source,feasible_alphas=feasible,largest_feasible_alpha=max(feasible) if feasible else None,converged_slots=sum(r['converged_slots'] for r in subset),control_complete_slots=sum(r['control_complete_slots'] for r in subset),solver_error_slots=sum(r['solver_error_slots'] for r in subset)))
    s.table(H/'SOURCE_GRID_SUMMARY.csv',source_rows)
    report=['# IEEE8500 source-grid compatibility operating point','',f'**{status}**','',f'Final (source_pu, alpha8500): **({authority["source_pu"]}, {authority["alpha8500"]})**. Selected date: **2025-05-21**.','', 'The source grid {1.050, 1.045, 1.040, 1.035, 1.030}, alpha grid {1.00, 0.95, ..., 0.00}, code, hard criteria, lexicographic selection rule and input hashes were frozen before execution. All **105 cases / 10,080 chronological B0 slots** were freshly evaluated. The original failed source=1.050 stage was independently reproduced across all 21 alpha trajectories and remains immutable.','', 'This is a reduced-load IEEE8500 study-envelope compatibility adaptation, **not canonical IEEE8500 reproduction**. Relative to the preceding adaptation, only source pu varies. All twelve regulator phase controls retain Vreg=125 V, PT ratio=60, band=2 V and original tap limits. CAPBank3 remains OFF; all nine controlled capacitor phases and CapControls, native impedances/topology/ratings, PCCs, 24-location registry and AIDC/MESS scales remain unchanged.','', 'Every case uses a fresh engine context, MaxIterations=100, MaxControlIterations=1000, native snapshot control mode and 96 sequential snapshots with accepted tap/cap state carried within the day. Five isolated source workers run concurrently; completion order is irrelevant to selection. No control EventLog property is edited. Inputs are the same frozen causal D-1 VIC1 demand/PV profiles, B0 exogenous PV penetration ratio, native proportional phase allocation and AIDC P/Q trajectories; MESS commands remain zero. No Actual or B1/B2/B3 data are used.','', '| Source pu | Feasible alpha values | Largest feasible alpha | Converged / settled slots |','|---:|:---|---:|:---:|']
    for r in source_rows:report.append(f'| {r["source_pu"]:.3f} | '+(', '.join(f'{a:.2f}' for a in r['feasible_alphas']) or 'None')+f' | {r["largest_feasible_alpha"]} | {r["converged_slots"]} / {r["control_complete_slots"]} |')
    report.extend(['','Selection uses the **largest source with any feasible alpha**, then the **largest feasible alpha at that source**. It does not select a lower source merely to improve alpha. All grid points are evaluated, with no refinement or post-result tuning.','', 'Hard limits: 0.95–1.05 pu at all 8639 nodes; line phase-current, transformer phase-current and transformer winding apparent-power loading ≤1.0 pu, with the unchanged 1e-9 numerical boundary tolerance. Both active line terminals and every transformer winding are included. Every slot must converge and settle controls.'])
    if accepted:
        c=chosen;report.extend(['','Selected case extrema:','', '| Quantity | Screening | Independent replay |','|:---|---:|---:|'])
        for k in ['Vmin_pu','Vmax_pu','max_phase_line_loading_pu','max_transformer_phase_current_pu','max_transformer_winding_kva_pu']:report.append(f'| {k} | {c[k]:.12f} | {replay["summary"][k]:.12f} |')
        report.extend(['',f'Independent replay **PASS**: a separate clean process and fresh context completed all 96 chronological slots. All voltage/current/kVA axes were independently reconstructed using scalar bus/element APIs. Maximum phase-array difference: {max(replay["max_absolute_phase_array_differences"].values()):.3g} pu. Physical accepted tap/cap states match, and no unexpected static changes occurred.'])
    else:report.extend(['', 'No final operating-point authority is accepted. Stop without additional tuning. Replay status: **'+replay['status']+'**.'])
    report.extend(['',f'All **{len(protected)} original evidence files** preserve SHA256, size and modification time. The previous NO_FEASIBLE_ALPHA_ON_FIXED_COMPATIBILITY_GRID result is untouched. Rule/code/input pre-execution hashes also remain unchanged.','', 'B1/B2/B3 executions: **0**. Additional tuning outside the frozen grid: **0**.','', 'Outputs: FINAL_OPERATING_POINT_AUTHORITY.json; SOURCE_GRID_SUMMARY.csv; SOURCE_ALPHA_SCREEN_TABLE.csv (105 cases); B0_10080_SLOT_EXTREMA.csv; per-case full phase arrays and control states under screen/; INDEPENDENT_REPLAY_VERIFICATION.json and independent_replay/; GRID_VALIDATION.json; IMMUTABILITY_FINAL_AUDIT.json; pre-execution and final SHA256 manifests.','', '## All 105 cases','', '| source | alpha | feasible | conv/settled | Vmin | Vmax | line I | transformer I | transformer kVA |','|---:|---:|:---:|:---:|---:|---:|---:|---:|---:|'])
    for r in rows:report.append(f'| {r["source_pu"]:.3f} | {r["alpha"]:.2f} | {r["feasible"]} | {r["converged_slots"]}/{r["control_complete_slots"]} | {r["Vmin_pu"]:.9f} | {r["Vmax_pu"]:.9f} | {r["max_phase_line_loading_pu"]:.9f} | {r["max_transformer_phase_current_pu"]:.9f} | {r["max_transformer_winding_kva_pu"]:.9f} |')
    (H/'IEEE8500_SOURCE_GRID_COMPATIBILITY_REPORT.md').write_text('\n'.join(report)+'\n',encoding='utf-8')
    mf=H/'SOURCE_GRID_EVIDENCE_FREEZE_MANIFEST.json';assert not mf.exists();files=[dict(path=str(p.relative_to(H)),sha256=s.sha(p),bytes=p.stat().st_size) for p in sorted(H.rglob('*')) if p.is_file() and p.name not in [mf.name,'SOURCE_GRID_EVIDENCE_FREEZE_MANIFEST.sha256']]
    s.save(mf,dict(frozen_at_utc=datetime.now(timezone.utc).isoformat(),status=status,source_pu=authority['source_pu'],alpha8500=authority['alpha8500'],canonical_reproduction=False,pre_execution_manifest_sha256=s.sha(H/'PRE_EXECUTION_FREEZE_MANIFEST.json'),protected_files_unchanged=len(protected),B0_screen_slots=10080,independent_replay_slots=replay['simulation_slots'],independent_replay_status=replay['status'],B1_B2_B3_runs=0,files=files));(H/'SOURCE_GRID_EVIDENCE_FREEZE_MANIFEST.sha256').write_text(s.sha(mf)+'  '+mf.name+'\n',encoding='ascii');print('FINAL_FREEZE_COMPLETE',status,authority['source_pu'],authority['alpha8500'],s.sha(mf),flush=True)
if __name__=='__main__':main()
