"""Frozen contracts for the V35R3I GPU-slot component-delta bridge."""

from __future__ import annotations


PARENT_HEAD = "549ce2aea231187a1df5f21b40fe49c5eb8c97a1"
BRANCH = "codex/v35r3i-semiempirical-h100-gpu-slot-power-bridge"
ARTIFACT_DIRNAME = "v35r3i_semiempirical_h100_gpu_slot_power_bridge"

GPU_CAPACITY = 624
GPUS_PER_NODE = 4
SLOT_HOURS = 0.25
APR01_SLOTS = 96
TARGET_OFFSET_SLOTS = 24
W1 = (74,)
W3 = (73, 74, 75)
W5 = (72, 73, 74, 75, 76)

FROZEN_IT_REFERENCE_KW = 406.77599381381907
AIDC_DELTA_SCALE = 1.0

# Direct Kestrel H100 idle measurement: 72.5 +/- 0.1 W/GPU.  The bounds
# deliberately reproduce the reported measurement spread and are not tuned
# against the scheduler result.
IDLE_POWER_W = {"LOW": 72.4, "CENTER": 72.5, "HIGH": 72.6}

SCENARIOS = ("LOW", "CENTER", "HIGH")

REQUIRED_ARTIFACTS = (
    "V35R3I_START_STATE.json",
    "V35R3I_ISOLATION_AUDIT.json",
    "V35R3I_PUBLIC_POWER_LITERATURE_AUTHORITY.json",
    "V35R3I_KESTREL_HARDWARE_CONTRACT.json",
    "V35R3I_RW_RSP_GPU_OCCUPANCY.csv",
    "V35R3I_GPU_OCCUPANCY_CONSERVATION.json",
    "V35R3I_EXPANDED_FLEX_POWER_COVERAGE.json",
    "V35R3I_H100_ACTIVE_GPU_POWER_AUTHORITY.json",
    "V35R3I_H100_ACTIVE_GPU_RUN_STATISTICS.parquet",
    "V35R3I_H100_IDLE_GPU_POWER_AUTHORITY.json",
    "V35R3I_GPU_SLOT_POWER_SCENARIOS.json",
    "V35R3I_RW_RSP_GPU_COMPONENT_POWER.csv",
    "V35R3I_RW_RSP_GPU_COMPONENT_ENERGY.json",
    "V35R3I_PARTIAL_SHARED_GPU_CONSERVATION.json",
    "V35R3I_WORKLOAD_CLASS_UNCERTAINTY.json",
    "V35R3I_FROZEN_AIDC_POWER_SCALE_AUDIT.json",
    "V35R3I_NON_GPU_DELTA_ASSUMPTION.json",
    "V35R3I_STRICT_F0_VS_EXPANDED_COMPARISON.json",
    "V35R3I_EXPANDED_AIDC_CASE_CANDIDATE_CONTRACT.json",
    "V35R3I_SITE_BINDING_AUDIT.json",
    "V35R3I_RW_RSP_AIDC_IT_CANDIDATE.csv",
    "V35R3I_POWER_DIRECTION_ROBUSTNESS.json",
    "V35R3I_SEMI_EMPIRICAL_AUTHORITY_DECISION.json",
    "V35R3I_NEXT_STEP_DECISION.json",
    "V35R3I_COMPUTE_ACCOUNTING.json",
    "V35R3I_REPAIR_LOG.json",
    "V35R3I_TEST_REPORT.json",
    "V35R3I_FINAL_REVIEW.json",
    "V35R3I_FINAL_REVIEW.md",
)

