"""Assemble measured matrix audits without fabricating pending performance."""
from v42_root.common import *

def main():
    b=read(OUT/'BASELINE_STRUCTURAL.json');rows=list(csv.DictReader((OUT/'BASELINE_ROW_DENSITY.csv').open()))
    runtime=next(r for r in rows if r['family']=='Runtime_completion_risk');tie=next(r for r in rows if r['family']=='tie')
    dump('TIE_MATRIX_AUDIT.json',dict(baseline_rows=int(tie['rows']),baseline_nonzeros=int(tie['nonzeros']),maximum_row_density=int(tie['maximum']),scientific_objective=False,six_scientific_levels=read(OUT/'PREREGISTRATION.json')['scientific_levels'],removal_candidates=['F2-T','F2-TR','F2-A','F2-C','F2-CRA'],replacement='CANONICAL_POST_TIE_SPEC.md',scientific_optimum_set_unchanged=True,old_rank_representative_not_claimed=True))
    candidates={p.name.removesuffix('_STRUCTURAL.json'):read(p) for p in OUT.glob('*_STRUCTURAL.json') if p.name!='BASELINE_STRUCTURAL.json'}
    dump('RUNTIME_COMPLETION_MATRIX_AUDIT.json',dict(baseline_rows=int(runtime['rows']),baseline_nonzeros=int(runtime['nonzeros']),baseline_maximum_row_density=int(runtime['maximum']),baseline_maximum_row_identity=runtime['maximum_row_identity'],candidate_measurements={k:dict(completion_nonzeros=d['family_nonzeros'].get('Runtime_completion_risk'),definition_nonzeros=d['family_nonzeros'].get('Runtime_count_definition',0),total_model_nonzeros=d['nonzeros']) for k,d in candidates.items()},coefficient_matching='full exact downstream vector; mismatch raises UNEQUAL_RUNTIME_COEFFICIENT_VECTOR',no_averaging=True))
    (OUT/'BASELINE_ROOT_LP_PROFILE.md').write_text(f'''# Independently reproduced original full-May matrix\n\nColumns {b['columns']:,}; rows {b['rows']:,}; nonzeros {b['nonzeros']:,}. Binary {b['binaries']:,}; general integer {b['integers']:,}; continuous {b['continuous']:,}. Matrix build used the complete 1,499-job native domain and all 96 electrical slots, without optimize. Build seconds during VHD compaction are not clean performance measurements.\n\nRuntime completion: {int(runtime['nonzeros']):,} nonzeros across {int(runtime['rows']):,} rows; maximum {int(runtime['maximum']):,} terms at {runtime['maximum_row_identity']} (zero-based matrix row {runtime['maximum_row_index']}). Non-scientific tie: {int(tie['nonzeros']):,} nonzeros across {int(tie['rows']):,} rows. Full row distributions and unique-column incidence/objective participation are in the baseline CSVs.\n\nInherited PR102 measured initial MIP root relaxation: 1,557.90 s, 457,124 iterations, objective 0.6716023396111563. Presolved rows/columns/nonzeros: 7,533,647 / 7,247,816 / 46,376,330. Its 3,600-s production run had one node and no incumbent; the evidence demonstrates root processing dominance, not branch-tree explosion. Matrix families identify compression opportunities but do not establish that any one family caused a particular number of solve seconds. Fresh continuous-P1 LP diagnostics will be measured only after the clean performance gate. Their total LP optimize wall includes LP presolve and is distinguished from the inherited MIP root-only time.\n''',encoding='utf8')
    dump('NUMERICAL_SCALING_AUDIT.json',dict(baseline=read(OUT/'BASELINE_NUMERICAL.json'),candidates={k:read(OUT/(k+'_NUMERICAL.json')) for k in candidates},exact_WAN_units='payload remaining/sent use rational GCD quantum; physical byte incidence preserved; F2-CRA WAN matrix and link variable use exactly 2**20 bytes per unit',physical_raw_bytes_preserved=True,scaled_candidate='F2-CRA',power_two_unit_conversion=1048576,Runtime_coefficients='unchanged bit-exact coefficient vectors',grid_coefficients='unchanged frozen C1/native equations',no_physical_capacity_change=True,warning='power-of-two WAN units improve one coefficient family; other numerical ranges and solver warnings remain measured'))
    for filename,ks,policy in [
        ('DEPART_ARRIVE_COMPRESSION_AUDIT.json',['F2-T','DA1','DA2','DA3'],'eliminate only if complete measured matrix improves; preserve derived nonnegative lower bounds and source/destination upper bounds'),
        ('LINK_BYTES_COMPRESSION_AUDIT.json',['F2-T','LINK'],'share only identical fixed-path incidence vectors; universal fixed links use exact sent expression; no routing freedom'),
        ('F0_COMPRESSION_AUDIT.json',['F2-T','F0','STATE'],'nonmigration finish is start+D; migration finish is retained; compare sparse state recurrences against histogram occupancy substitution')]:
        dump(filename,dict(measurements={k:candidates[k] for k in ks if k in candidates},policy=policy,exactness='FORMULATION_EXACTNESS.json',selection_pending=len([k for k in ks if k in candidates])!=len(ks)))
if __name__=='__main__':main()
