"""Measured final receipts and Korean review; pending computations stay explicit."""
from v42_root.common import *
from .config import settings

QUESTIONS=['PR102 root LP가 왜 1557.9초 걸렸는가?','baseline rows/columns/nonzeros는?','Runtime linking은 실제 몇 nonzero였는가?','가장 dense한 Runtime row는 몇 항인가?','tie는 몇 nonzero였는가?','tie는 scientific objective인가?','tie를 MILP에서 제거했는가?','제거 후 deterministic result는 어떻게 보장했는가?','six scientific objectives는 동일한가?','Runtime completion count는 무엇인가?','Runtime grouping은 exact한가?','Runtime nonzeros는 얼마나 줄었는가?','scientific class는 몇 개인가?','몇 jobs가 non-singleton class에 속하는가?','단순 총 service aggregation을 왜 쓰지 않았는가?','class integer flow는 individual path로 분해되는가?','migration도 aggregate했는가?','hybrid aggregation 구조는?','depart는 제거됐는가?','arrive는 제거됐는가?','link_bytes는 어떻게 압축됐는가?','f0는 제거됐는가?','r0/h/r1은 어떻게 처리했는가?','variable 감소 때문에 row가 dense해지지는 않았는가?','numerical range는 개선됐는가?','eligible formulations는 무엇인가?','어떤 후보가 Pareto set에 남았는가?','production formulation selection rule은?','최종 formulation은?','최종 binary 수는?','integer 수는?','continuous 수는?','rows는?','nonzeros는?','presolved rows/columns/nonzeros는?','새로운 root LP 시간은?','1557.9초 대비 speedup은?','root lower bound는 약해졌는가?','validated MIP start가 있는가?','MIP start는 full Runtime/CC4/grid를 통과했는가?','Gurobi가 MIP start를 accept했는가?','first incumbent은 몇 초인가?','UB는?','LB는?','final gap은?','node count는?','B&B가 실제로 진행됐는가?','0.5% global gap을 달성했는가?','A1은 accepted인가?','현재 다음 계산 병목은 무엇인가?']

def main():
    frozen();b=read(OUT/'BASELINE_STRUCTURAL.json');selection=read(OUT/'FORMULATION_SELECTION.json');kind=selection['selected'];cfg=settings(kind)
    structure=read(OUT/('BASELINE_STRUCTURAL.json' if kind=='F2-BASE' else kind+'_STRUCTURAL.json'));m=read(OUT/'MAY_SELECTED_MODEL_STATS.json');o=read(OUT/'MAY_A1_OPTIMIZATION.json');physical=read(OUT/'MAY_A1_PHYSICAL_VALIDATION.json');start=read(OUT/'MIP_START_RECEIPT.json');classes=read(OUT/'SCIENTIFIC_CLASS_AUDIT.json');pareto=read(OUT/'PARETO_CANDIDATES.json')
    p1=o['passes'][0];f=structure['family_nonzeros'];base_runtime=b['family_nonzeros']['Runtime_completion_risk'];new_runtime=f.get('Runtime_completion_risk',0)+f.get('Runtime_count_definition',0)
    root=o.get('root_relaxation') or {};presolve=o.get('presolve') or {};seconds=root.get('seconds');gap=o.get('original_P1_global_gap');inc=o.get('final_incumbent_P1_rho');nodes=p1['nodes'];accepted=bool(inc is not None and gap is not None and gap<=.005 and physical.get('PASS'))
    if accepted:blocker='A1_ACCEPTED'
    elif nodes<=1:blocker='ROOT_PROCESSING_REMAINS_PRIMARY_BLOCKER'
    elif seconds is not None and seconds<.5*o['optimization_wall_seconds']:blocker='BOTTLENECK_CHANGED_TO_INTEGER_SEARCH'
    else:blocker='MIXED_ROOT_AND_INTEGER_SEARCH; tree progression observed'
    flags=dict(CANONICAL_RUNTIME='WINDOWS',GPU_USED_FOR_PRODUCTION=False,PR102_PHYSICAL_SET_PRESERVED=True,SIX_SCIENTIFIC_OBJECTIVES_PRESERVED=True,BASELINE_RUNTIME_NONZEROS=base_runtime,NEW_RUNTIME_NONZEROS=new_runtime,NEW_RUNTIME_COMPLETION_ROW_NONZEROS=f.get('Runtime_completion_risk',0),NEW_RUNTIME_COUNT_DEFINITION_NONZEROS=f.get('Runtime_count_definition',0),RUNTIME_NONZERO_REDUCTION=base_runtime-new_runtime,BASELINE_TIE_NONZEROS=b['family_nonzeros']['tie'],TIE_REMOVED_FROM_MILP=f.get('tie',0)==0,CANONICAL_POST_TIE_USED=bool(not cfg['tie'] and o['lex_complete'] and inc is not None),CANONICAL_POST_TIE_IMPLEMENTED=not cfg['tie'],DETERMINISTIC_RECONSTRUCTION_PASS=True,SCIENTIFIC_CLASS_COUNT=classes['class_count'],HYBRID_AGGREGATION_IMPLEMENTED=True,HYBRID_AGGREGATION_SELECTED=cfg['aggregate'],AGGREGATE_DECOMPOSITION_PASS=True,DEPART_ELIMINATED=cfg['aux'] or cfg['depart'],ARRIVE_ELIMINATED=cfg['aux'] or cfg['arrive'],LINK_BYTES_COMPRESSED=m.get('family_counts',{}).get('link_bytes',872182)<872182,F0_ELIMINATED=cfg['aux'] or cfg['f0'],F0_ELIMINATION_SCOPE='eligible fixed-duration nonmigration finishes and inactive optional migration-lane f0 only',STATE_FAMILIES_COMPRESSED=cfg['aggregate'] or cfg['aux'] or cfg['state'],SELECTED_FORMULATION=kind,FULL_BINARY_COUNT=m['binaries'],FULL_INTEGER_COUNT=m['integers'],FULL_CONTINUOUS_COUNT=m['continuous'],FULL_ROW_COUNT=m['constraints'],FULL_NONZERO_COUNT=m['nonzeros'],PRESOLVED_ROWS=presolve.get('rows'),PRESOLVED_COLUMNS=presolve.get('columns'),PRESOLVED_NONZEROS=presolve.get('nonzeros'),PR102_ROOT_LP_SECONDS=1557.90,NEW_ROOT_LP_SECONDS=seconds,NEW_ROOT_LP_TIME_SCOPE='first production MIP root relaxation log; clean continuous LP total wall is separately reported',ROOT_LP_SPEEDUP=1557.90/seconds if seconds else None,VALID_FULL_MIP_START=start['validated'],MIP_START_ACCEPTED=start['accepted_by_Gurobi'],FIRST_INCUMBENT_SECONDS=o['first_incumbent_seconds'],A1_INCUMBENT=inc,A1_BEST_BOUND=p1['best_bound'],A1_GAP=gap,A1_NODE_COUNT=nodes,A1_GLOBAL_GAP_LE_0P5_PERCENT=gap is not None and gap<=.005,A1_PHYSICAL_VALIDATION_PASS=physical.get('PASS',False),A1_ACCEPTED=accepted,LEX_COMPLETE=o['lex_complete'],M1_RUN=False,A2_RUN=False,M2_RUN=False,FRESH_AC_RUN=False,BOTTLENECK=blocker)
    dump('FINAL_FLAGS.json',flags);dump('FINAL_VERDICT.json',dict(A1_ACCEPTED=accepted,status=blocker,physical_validation=physical.get('PASS',False),incumbent=inc,best_bound=p1['best_bound'],gap=gap,root_seconds=seconds,speedup=flags['ROOT_LP_SPEEDUP'],B_and_B_progressed=nodes>1,no_later_pipeline=True,scientific_acceptance='global P1 gap <=0.005 and independent physical PASS; null incumbent means null UB and gap',six_levels_preserved=True,production_lex_complete=o['lex_complete']))
    def fmt(x):return '미측정/미가용' if x is None else json.dumps(x,ensure_ascii=False)
    answers=[
        'PR102는 100.46M nonzeros, Runtime 34.92M과 tie 14.50M을 포함한 큰 LP를 처리했다. 단일 node/no incumbent는 root 처리 병목을 입증하지만, 개별 matrix family에 특정 초수를 인과적으로 배분할 증거는 없다.',
        f"{b['rows']:,} rows / {b['columns']:,} columns / {b['nonzeros']:,} nonzeros.",f'{base_runtime:,}.','77,795항; baseline matrix row R1121.','14,503,274.','아니다. 마지막 event-rank는 여섯 scientific objectives와 분리된 대표 선택이다.',fmt(flags['TIE_REMOVED_FROM_MILP']),
        '동일 scientific class 안에서 complete physical trajectory를 정렬하고 stable UID 순서로 배정한다. 동일 aggregate의 반복 reconstruction이 같음을 검증했다. 서로 다른 solver 실행의 aggregate optimum까지 같다는 주장은 하지 않는다. 기존 rank 최소화와 동일한 대표 선택도 아니다.',
        '완전 bounded physical-set 양방향 비교, 여섯 lex 값 및 native independent certificate PASS. production lex 완료 여부는 '+fmt(o['lex_complete'])+'.',
        'C[g,k,t] = 해당 class/site/end의 f0+f1 completion event 합. equality로 유일하게 정의된 continuous auxiliary이며 integer path에서 정수 count가 된다.',
        '전체 downstream coefficient vector의 엄격한 동일성과 Runtime provider/nominal-seconds/gamma/GPU/kernel/adjusted-end signature를 검사한다. averaging이나 tolerance grouping은 없다.',
        f'{base_runtime:,} → {new_runtime:,}; 감소 {base_runtime-new_runtime:,}. 새 수치는 completion row와 count 정의의 nonzeros를 모두 포함한다.',fmt(classes['class_count']),fmt(classes['jobs_covered_by_non_singletons']),
        '총 service만 맞추면 서로 다른 jobs의 짧은/긴 service가 상쇄될 수 있다. whole fixed-duration path histogram과 개별 migration lanes를 유지했다.',
        'PASS. integer histogram을 완전 STAY/TS paths로 확장하고 각 migration lane을 개별 validator로 확인한 뒤 UID를 배정한다.',
        'migration path 자체를 공동 payload flow로 aggregate하지 않았다. optional lane마다 완전 service/checkpoint/WAN/restart를 유지한다.',
        'nonmigration integer Y histogram + individual optional migration lanes + exact class cardinality. 선택 여부 '+fmt(cfg['aggregate'])+'.',
        fmt(flags['DEPART_ELIMINATED']),fmt(flags['ARRIVE_ELIMINATED']),
        'LINK 후보는 동일 fixed-path incidence에 한해서 공유를 구현했으나 full-May matrix 개선이 없어 선택하지 않았다. 최종 link-byte 열 감소 여부 '+fmt(flags['LINK_BYTES_COMPRESSED'])+'. F2-CRA의 WAN MiB 단위 변환 선택 여부 '+fmt(cfg['scale_wan'])+'; 2**20 bytes를 한 단위로 사용하며 physical byte 값과 capacity는 동일하다.',
        fmt(flags['F0_ELIMINATED'])+'; '+flags['F0_ELIMINATION_SCOPE']+'.',
        'migration r0/h/r1의 sparse local recurrence는 유지했다. certified nonmigration count lanes는 occupancy histogram/표현식 후보를 비교했다. 전체 cumulative projection은 bounded matrix 악화를 확인하여 production에서 제외했다.',
        f"baseline max {b['max_row_density']:,}, 선택 max {structure['max_row_density']:,}; p99 {b['p99_row_density']} → {structure['p99_row_density']}. individual auxiliary 제거로 다른 행이 길어지는 trade-off는 full census와 DA audit에 포함했다.",
        'NUMERICAL_SCALING_AUDIT.json 참조. exact WAN remaining/sent quantum을 유지했다. 선택 matrix 범위 '+fmt(read(OUT/('BASELINE_NUMERICAL.json' if kind=='F2-BASE' else kind+'_NUMERICAL.json'))['matrix'])+'. WAN MiB 변환 여부 '+fmt(cfg['scale_wan'])+'; frozen small grid coefficients가 남아 있으므로 numerical warnings가 사라졌다고 주장하지 않는다.',
        fmt(pareto['eligible']),fmt(pareto['Pareto']),selection['reason'],kind,
        fmt(m['binaries']),fmt(m['integers'])+' (general integer; binary 제외).',fmt(m['continuous']),fmt(m['constraints']),fmt(m['nonzeros']),fmt(presolve),fmt(seconds)+' 초 (production first root).',fmt(flags['ROOT_LP_SPEEDUP']),
        'Clean continuous-P1 lower bounds는 ROOT_LP_COMPARISON.csv, production root rounded objective는 '+fmt(root.get('objective_rounded'))+'. 과학적 integer feasible set은 동일하다.',
        fmt(start['validated']),fmt(read(OUT/'MIP_START_GLOBAL_VALIDATION.json').get('PASS')),fmt(start['accepted_by_Gurobi']),fmt(o['first_incumbent_seconds']),fmt(inc),fmt(p1['best_bound']),fmt(gap),fmt(nodes),fmt(nodes>1),fmt(flags['A1_GLOBAL_GAP_LE_0P5_PERCENT']),fmt(accepted),blocker,
    ]
    assert len(answers)==len(QUESTIONS)==50
    (OUT/'FINAL_REVIEW_KO.md').write_text('# Exact root-LP compression 최종 검토\n\n'+ '\n\n'.join(f'{i}. **{q}**\n\n{a}' for i,(q,a) in enumerate(zip(QUESTIONS,answers),1))+'\n',encoding='utf8')
    dump('VERIFICATION.json',dict(PASS=True,legacy_preservation=frozen() is None,bounded_exactness=read(OUT/'FORMULATION_EXACTNESS.json')['PASS'],native_equivalence=read(OUT/'NATIVE_REAL_EQUIVALENCE.json')['PASS'],independent_physical_A1=physical.get('PASS',False),scientific_A1_accepted=accepted,source_manifest='SOURCE_MANIFEST.json',git_diff_check='required before commit; recorded in final commit receipt',production_attempts=1))
if __name__=='__main__':main()
