"""Seal evidence before cleanup; copy only Windows audit outputs, never science/input manifests."""
import json,shutil,re,subprocess,hashlib
from pathlib import Path
H=Path.home();R=H/'mobileess_worktrees/root_lp_compression';O=R/'docs/v42_ubuntu_gpu_migration';W=Path('/mnt/d/ChatGPT/Mobile ESS 2/v42_root_lp_compression_pr/docs/v42_ubuntu_gpu_migration')
for name in ('CURRENT_WIP_CHECKPOINT.json','WINDOWS_MOBILEESS_STORAGE_INVENTORY.csv','WINDOWS_PATH_LINKS.json','WINDOWS_OLD_ENVIRONMENT_REFERENCES.txt','IEEE8500_WINDOWS_SCAN_RECEIPT.json','IEEE8500_WINDOWS_GIT_STATE.json','WINDOWS_IEEE8500_REFS.json','WSL_STORAGE_AUDIT.json','cleanup_windows.ps1'):
    assert (W/name).exists(),name;shutil.copy2(W/name,O/name)
scan=json.loads((O/'IEEE8500_WINDOWS_SCAN_RECEIPT.json').read_text())
scan.update(inventory_error_disposition='Only reported error is a non-IEEE long-path regression fixture. Its source folder remains UNKNOWN/protected and was not deleted. The IEEE8500 hashed file manifest has no unresolved copy/hash error.',error_in_IEEE8500_path=False,source_folder_retained=True)
(O/'IEEE8500_WINDOWS_SCAN_RECEIPT.json').write_text(json.dumps(scan,ensure_ascii=False,indent=2)+'\n')
b=json.loads((O/'PR102_GPU_ROOT_BENCHMARK.json').read_text());log=(O/'PR102_GPU_ROOT.log').read_text();stage=re.search(r'PDHG solved model in ([\d.]+) iterations and ([\d.]+) seconds',log)
b.update(GPU_stage_reported_seconds=float(stage[2]) if stage else None,post_PDHG_CPU_refinement_elapsed_approx_seconds=b['solver_runtime']-float(stage[2]) if stage else None,crossover_separate_seconds=None,crossover_timing_scope='No separate crossover timer in log; post-PDHG elapsed estimate includes refinement and overhead. Zero PDHG iterations, then CPU simplex.',prior_Windows_continuous_LP_objective=.6715992598027204,objective_delta_from_prior_Windows_LP=b['objective']-.6715992598027204,objective_delta_from_prior_native_MIP_root=b['objective']-b['prior_CPU_native_MIP_root_objective'],historical_CPU_wall_divided_by_GPU_wall=1557.9/b['wall_seconds'],strict_numerical_bound_validation=False,GPU_for_next_production_A1=False,decision='Computational execution and VRAM fit verified; no acceleration or strict bound certification. Preserve solver numerical warnings and prioritize exact CPU formulation compression.')
(O/'PR102_GPU_ROOT_BENCHMARK.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('# Canonical Ubuntu V42 migration\n\nCanonical distro Ubuntu-MobileESS-D (WSL2), Linux worktrees under /home/jaewon/mobileess_worktrees. Scientific WIP checkpoint a88879f is pushed. PR102 exact SHA and full model structure/tests verified, GPU smoke and full-May continuous diagnostic complete. IEEE preservation and Windows per-path cleanup/post-restart validation are tracked in separate receipts; no pending gate is claimed complete. No production A1 was run. Full-May GPU diagnostic is slower than historical CPU reference and has numerical warnings, so GPU is not selected for future production A1.\n')
print('PRE_CLEANUP_EVIDENCE_SEALED',flush=True)
