"""Verify effective adapter parameters before the fresh B2 launch."""
from bootstrap import *
import ast, inspect
import gurobipy as gp
from dayahead.v34 import integrated_mess as original
from dayahead.v40a import recourse
import mess_runtime

def main():
    transition=read(H/'PAPER_TERMINATION_TRANSITION.json')
    assert transition['status']=='PRESERVED_AND_STOPPED'
    source=Path(inspect.getsourcefile(original.solve_integrated_mess))
    assert sha(source)=='fb92793b9bc8cada5fb09bbf5c3c866cc644e18a052ee1fa97494d09bfa6ea32'
    adapted=mess_runtime.integrated_adapter('PAPER_TERMINATION_PREFLIGHT',profile_mode=True,grid_mode='active_seed')
    ns=adapted.__globals__
    assert ns['_configured_model'] is original._configured_model
    assert ns['WORK_LIMIT_TIERS']==original.WORK_LIMIT_TIERS==(60.,180.,300.)
    model=ns['_configured_model']('paper_termination_parameter_probe')
    keys=('TimeLimit','WorkLimit','MIPGap','Threads','Seed','FeasibilityTol','OptimalityTol','MIPFocus','SoftMemLimit','NodefileStart')
    params={k:getattr(model.Params,k) for k in keys}
    assert params['TimeLimit']==600. and params['WorkLimit']==60. and params['MIPGap']==.001
    assert params['Threads']==4 and params['SoftMemLimit']==8.
    model.dispose()
    text=read(H/'PAPER_TERMINATION_PREFLIGHT/solver_trace/ADAPTED_SOURCE_PROFILE.json')['adapted_source']
    tree=ast.parse(text); original_tree=ast.parse(inspect.getsource(original.solve_integrated_mess))
    def objective(tree):
        return [ast.dump(n,include_attributes=False) for n in ast.walk(tree)
                if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and n.func.attr=='setObjective']
    assert objective(tree)==objective(original_tree)
    acceptance='accepted_statuses = {GRB.OPTIMAL, GRB.WORK_LIMIT, GRB.TIME_LIMIT, GRB.SUBOPTIMAL}'
    assert acceptance in text
    assert 'FULL_MODEL_INCUMBENT_WORSE_THAN_BEST_RESTRICTED_FEASIBLE_INCUMBENT' in text
    assert 'V35_MESS_FULL_MODEL_WORSE_THAN_RESTRICTED_INCUMBENT' in text
    runtime_text=(H/'mess_runtime.py').read_text(encoding='utf-8')
    assert 'model.Params.TimeLimit=gp.GRB.INFINITY' not in runtime_text
    assert 'model.Params.WorkLimit=gp.GRB.INFINITY' not in runtime_text
    recourse_before=recourse._configured_model
    assert 'old._configured_model=' not in inspect.getsource(mess_runtime.recourse)
    # Exercise the actual production active-separation wrapper with deterministic
    # fake solver receipts: WORK_LIMIT + incumbent + full separation is accepted;
    # all violations require another solve; no-incumbent returns to tier escalation.
    # No mathematical solve or production result is generated by this check.
    production=mess_runtime.integrated_adapter('PAPER_TERMINATION_PREFLIGHT',grid_mode='active_seed')
    g=production.__globals__
    from types import SimpleNamespace
    class ProbeModel:
        NumVars=1;NumBinVars=1;NumConstrs=1;NumNZs=1;NumQConstrs=0;NodeCount=0.
        def __init__(self,status,solutions):
            self.Params=SimpleNamespace(MIPGap=.001,Threads=4,TimeLimit=600.,WorkLimit=60.,NodeLimit=gp.GRB.INFINITY,
                SoftMemLimit=8.,MIPFocus=1)
            self.Status=status;self.SolCount=solutions;self.ObjVal=.9;self.ObjBound=.89;self.MIPGap=.011111
            self.solves=0
        def update(self):pass
        def optimize(self,callback):self.solves+=1
    active=g['full_active_optimize'].__closure__
    cells=dict(zip(g['full_active_optimize'].__code__.co_freevars,[c.cell_contents for c in active]))
    module=cells['active_module']
    class ProbeGrid:
        report_root=H/'PAPER_TERMINATION_PREFLIGHT/fake_separation'
        def __init__(self):self.calls=0
        def separate(self):
            self.calls+=1
            return dict(new_rows=1 if self.calls==1 else 0,all_logical_rows_checked=31945536,
                maximum_violation=0.,exact_original_row_tolerance=1e-6)
    module.ACTIVE=ProbeGrid()
    model=ProbeModel(gp.GRB.WORK_LIMIT,1)
    assert g['full_active_optimize'](model)==1 and model.solves==2
    model=ProbeModel(gp.GRB.TIME_LIMIT,0)
    assert g['full_active_optimize'](model)==0 and model.solves==1
    module.ACTIVE=None
    report=dict(status='PASS',user_authority='Restore paper termination and restart B2 from scratch',
        B2_restart_from_scratch=True,reuse_prior_B2_solutions=False,reuse_prior_B2_candidate_cache=False,
        effective_parameters=params,WORK_LIMIT_TIERS=list(original.WORK_LIMIT_TIERS),
        accepted_statuses=['OPTIMAL','WORK_LIMIT','TIME_LIMIT','SUBOPTIMAL'],
        feasible_incumbent_required=True,original_quality_guard_unchanged=True,
        full_separation_required=True,exact_AC_96_slots_required=True,
        production_sparse_wrapper_probe='PASS',objective_AST_equal=True,
        original_source=record(source),current_runtime=record(H/'mess_runtime.py'),
        recourse_configured_model_source=record(inspect.getsourcefile(recourse_before)),
        supersedes=['MESS_NO_CUTOFF_AUDIT.json','B2_ACTIVE_PRODUCTION_PRELAUNCH.json'],
        sparse_separation_note='Each restricted optimize uses paper limits; every violated original row is added until full feasibility closure; original outer tiers and quality guard remain',
        snapshot=transition['diagnostic'],unix=time.time())
    save(H/'PAPER_SOLVER_TERMINATION_AUTHORITY.json',report)
    print('PAPER_TERMINATION_PREFLIGHT_PASS',params,flush=True)

if __name__=='__main__':main()
