from v42_a_stage_lexcases.policy import ROOT,OUT,STATIC,DAY,POLICY as CASE_POLICY
POLICY=dict(CASE_POLICY,schema='A_PRACTICAL_FULL_DOMAIN_WEIGHTED_CG_V1',valid_integer_cuts='EXACT_WEIGHTED_HISTOGRAM_CAPACITY_ROUNDING')
