from .common import *
import subprocess
REQUIRED='''ULTRACOMPACT_PREREGISTRATION.md C2_BASE_IDENTITY.json C2_PRESOLVE_FORENSIC.json C2_PRESOLVE_CANDIDATE_MAP.csv EXHAUSTIVE_ROW_FAMILY_AUDIT.csv EXHAUSTIVE_COLUMN_FAMILY_AUDIT.csv EXHAUSTIVE_REDUCTION_LEDGER.csv CORRELATED_ROUTE_SOC_PQ_SUPPORT.md GROUPED_SUPPORT_DIRECTIONS.json LINE_THERMAL_SECOND_PASS.csv PCS16_FACE_AUDIT.csv POLYTOPE_MINIMAL_H_REPRESENTATION.json TRANSFORMER_FACE_AUDIT.csv VOLTAGE_SECOND_PASS.csv ROUTE_FLOW_STATE_EQUIVALENCE.json GRAPH_BISIMULATION_AUDIT.json TRANSIT_CHAIN_CONTRACTIONS.csv FLOW_RANK_AUDIT.json NODE_ACTIVITY_LINK_AUDIT.csv MODE_LOGIC_AUDIT.csv ENERGY_BALANCE_AUDIT.csv INJECTION_AUXILIARY_AUDIT.csv LINE_RESPONSE_AUXILIARY_AUDIT.csv TRANSFORMER_RESPONSE_AUDIT.csv RADIAL_TOPOLOGY_REFORMULATION.md GLOBAL_EQUALITY_RANK_AUDIT.json SPARSE_SUBSTITUTION_LEDGER.csv BOUND_TIGHTENING_V2.csv OBJECTIVE_SPECIFIC_CANDIDATES_ONLY.csv STATIC_REDUCTION_ROUNDS_V2.csv C3A_CENSUS.json C3B_CENSUS.json C3C_CENSUS.json C3_PRESOLVED_CENSUS.json ULTRACOMPACT_FIXTURE_RESULTS.json ULTRACOMPACT_ADVERSARIAL_RESULTS.json ULTRACOMPACT_INDEPENDENT_VERIFICATION.json ULTRACOMPACT_START_VALIDATION.json ULTRACOMPACT_SELECTION.json'''.split()
STATEMENTS=[
'이번 작업은 PR161의 selected C2 exact formulation을 기준으로 남아 있는 모든 row/column family를 전수 감사하고, C2의 continuous relaxation에서도 수학적으로 중복·고정·함의·결정적임이 증명된 구조만 추가 제거한 exact ultra-compact reformulation 연구다.',
'행 수를 줄이는 것 자체가 목적이 아니며, integer-only redundancy가 있지만 LP relaxation을 강화하는 제약은 primary C3에 유지했다.',
'line thermal, PCS16, route-flow, grid-response family까지 family-level 구조를 재검토했으며, 증명되지 않은 삭제 후보는 모두 유지했다.',
'최종 선택은 모델 크기가 아니라 root completion/time/Work, B&B node progress, valid global bound 및 valid MIP gap 개선으로 판정했다.']
def gate():
    C2=read('C2_BASE_IDENTITY.json')['census'];c=read('C3A_CENSUS.json');p2=read('C2_PRESOLVE_FORENSIC.json')['presolved'];p3=read('C3A_PRESOLVED_CENSUS.json')['presolved'];ratios={k:1-c[k]/C2[k] for k in ['rows','nnz','continuous']};pr={k:1-p3[k]/p2[k] for k in ['rows','nnz']};passed=max(ratios.values())>=.1 or max(pr.values())>=.15
    write('C3_PRESOLVED_CENSUS.json',dict(PASS=True,C2=p2,C3A=p3,C3B=p3,C3C=p3,distinct_native_presolve_calls=1,C3_candidates_exactly_identical=True,smaller_pre_but_larger_presolved=any(p3[k]>p2[k] for k in ['rows','columns','nnz']),presolved_increased_dimensions={k:p3[k]-p2[k] for k in ['rows','columns','nnz'] if p3[k]>p2[k]},retained_coefficients_byte_exact=True,coefficient_range_C2=C2['coefficient_range'],coefficient_range_C3=c['coefficient_range'],range_change_due_only_to_certified_row_removal=True))
    write('MATERIALITY_GATE.json',dict(PASS=passed,pre_reduction=ratios,presolved_reduction=pr,threshold_pre=.1,threshold_presolved=.15,root_and_MILP_authorized_if_resource_safe=passed))
    if not passed:write('ULTRACOMPACT_SELECTION.json',dict(PASS=True,state='ADDITIONAL_COMPRESSION_LOW_VALUE',selected=False,selected_formulation='FROZEN_PR161_C2',exactness=True,benchmarks_executed=False,STOP=True))
    print('MATERIALITY_GATE',passed,ratios,pr,flush=True)
def run():
    s=read('ULTRACOMPACT_SELECTION.json');a=read('AUDIT_SUMMARY.json');base=read('C2_BASE_IDENTITY.json');c=read('C3A_CENSUS.json');p2=read('C2_PRESOLVE_FORENSIC.json')['presolved'];p3=read('C3_PRESOLVED_CENSUS.json')['C3A'];v=read('ULTRACOMPACT_INDEPENDENT_VERIFICATION.json');start=read('ULTRACOMPACT_START_VALIDATION.json');bench=(OUT/'ULTRACOMPACT_MILP_COMPARISON.json').exists();root=read('ULTRACOMPACT_ROOT_COMPARISON.json') if bench else None;milp=read('ULTRACOMPACT_MILP_COMPARISON.json') if bench else None;source=milp['C3']['source_commit'] if bench else subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();pub=read('PUBLICATION.json') if (OUT/'PUBLICATION.json').exists() else None;pr=pub['PR_URL'] if pub else 'Draft PR 생성 예정; 실행 소스 커밋은 아래 기록'
    def size(x):return f"{x['rows']:,}행 / {x['columns']:,}열 / B {x['binaries']:,} / C {x['continuous']:,} / nnz {x['nnz']:,}"
    def metric(stage,key):return f"C2 {stage['C2'][key]} / C3 {stage['C3'][key]}" if stage else '미실행 — 최종 상태와 gate 참조'
    rows=a['rows_by_family'];q=[
    ('C2 원래 크기',size(base['census'])),('C2 presolved 크기',size(p2)),('추가 duplicate rows',str(a['proof_counts'].get('EXACT_DUPLICATE',0))),('추가 dominated rows',f"PCS/연결 Q 다중 제약 함의 {rows.get('PCS16',0)+rows.get('connected_Qmax',0)+rows.get('connected_Qmin',0):,}; 단일 비례 지배 {a['proof_counts'].get('EXACT_PROPORTIONAL_DOMINANCE',0):,}"),('추가 line thermal 삭제',f"{rows.get('line_thermal_face',0):,}"),('추가 PCS16 삭제',f"{rows.get('PCS16',0):,}"),('추가 transformer 삭제',f"{rows.get('transformer_kVA',0):,}"),('추가 voltage 삭제',f"{rows.get('voltage_upper',0)+rows.get('voltage_lower',0):,}"),('Flow conservation 종속행',f"종단 위치 4행은 실제 retained flow 등식의 합; flow 자체 삭제 {rows.get('flow',0)}행"),('node activity link 삭제',str(rows.get('node_activity_link',0))),('mode/connection rows 삭제',f"connected_Qmax/min {rows.get('connected_Qmax',0)+rows.get('connected_Qmin',0):,}; P 연결/충방전 mode 행은 0"),('energy balance 삭제',str(rows.get('energy_balance',0))),('route flow 변수 삭제','0'),('state 병합','0'),('transit chain 축약','0'),('grid auxiliaries 삭제','0'),('response auxiliaries 삭제','0'),('injection auxiliaries 삭제','0'),('continuous 삭제 합계','0'),('새 binary fix','0'),('새 bound tightening',f"{a['new_bounds']:,}개 열의 함의된 경계 전환; 모두 독립 검증"),('Polygon face count 축소','PCS16 16→10; P 연결 영역을 포함한 최소 H facet은 12; line/transformer 비상수 normalized polygon은 16'),('더 작은 exact extended formulation','채택 없음. 유리수 barycentric lift는 상태당 3행/12열/40 nnz로 최소 PCS 10행/0 추가열/36 nnz보다 열·nnz 증가; 일부 정점은 binary64 비표현 가능'),('C3A 크기',size(c)),('C3B 크기',size(read('C3B_CENSUS.json'))),('C3C 크기',size(read('C3C_CENSUS.json'))),('Presolved C3 vs C2',size(p3)+'; C2 '+size(p2)+f"; 역증가 flag={read('C3_PRESOLVED_CENSUS.json')['smaller_pre_but_larger_presolved']}"),('1536 assignment equivalence','PASS; 기존 12 fixture를 변경하지 않고 F0/C2/C3 모두 같은 feasible assignment와 목적값'),('Fractional LP proof','PASS; 비음수 Farkas 조합·flow 등식 합·단위 DAG 질량 max-union support; integer-only 삭제 0'),('Adversarial tests','PASS; '+str(read('ULTRACOMPACT_ADVERSARIAL_RESULTS.json')['tests'])+'개 신규 경우 및 독립 인증 변조 거절'),('Independent verification','PASS; C2 전체 행/열과 모든 새 bound, 제거행을 재구성; production deletion 함수 미호출'),('Start mapping',f"PASS; 물리 route/P/Q/SOC/mode 변경 0, 최대 잔차 {start['maximum_row_residual']:.17g} ≤ 1e-8"),('Root time C2 vs C3','micro '+metric(root,'root_time')+'; full MILP root '+metric(milp,'root_time')),('Root Work C2 vs C3','micro '+metric(root,'root_Work')+'; full MILP root '+metric(milp,'root_Work')+'; overall Work와 분리'),('Nodes C2 vs C3',metric(milp,'node_count')),('Valid LB',metric(milp,'valid_LB')),('Valid UB',metric(milp,'valid_UB')),('Valid gap',metric(milp,'valid_gap')+'; MIPGap=.005 유지'),('Selected',str(s['selected'])+'; '+s['selected_formulation']),('Exact commit / Draft PR',source+' / '+pr)]
    lines=['# PR161 C2 exact ultra-compact 전수 감사', '',f"최종 상태: **{s['state']}**",'',f"기준: `{BASE}` / Draft PR161. 추가 {a['new_rows_removed']:,}행을 full-LP 증명으로 제거했다. C3A=C3B=C3C이며 추가 치환·병합은 채택하지 않았다.",'']
    if bench and s.get('matched_full_MILP_root'):
        pair=s['matched_full_MILP_root']
        lines += [f"선택: {s['selected_formulation']}, selected={s['selected']}. 동일한 full MILP 설정의 새 C2/C3 root 비교에서 시간 {milp['C2']['root_time']:.2f}→{milp['C3']['root_time']:.2f}초 ({pair['root_time_reduction']:.2%} 감소), root Work {milp['C2']['root_Work']:.2f}→{milp['C3']['root_Work']:.2f} ({pair['root_Work_reduction']:.2%} 감소)로 사전 등록한 15% 기준을 충족했다. 두 arm 모두 root 이후 B&B node 0, 새 valid incumbent 없음, valid gap 약 {milp['C3']['valid_gap']:.4%}이며 LB/gap 개선 기준은 통과하지 않았다.",'', 'Micro C2의 root는 제한 시간 내 미완료했다. 표의 None은 미완료에 따른 측정 불가이며 0을 뜻하지 않는다. Micro와 full MILP 사이 또는 과거 PR161 실행과의 시간/Work 비교는 사용하지 않았다. 원래 micro-only 자동 판정은 별도 파일에 보존하고, 새 native 실행 없이 완료된 full MILP 쌍의 root 지표에 같은 사전 기준 A/B를 적용했다.','']
    for statement in STATEMENTS:lines += [statement,'']
    lines+=['## 필수 검토 40문항','','| 번호 | 질문 | 답변 |','|---:|---|---|'];lines.extend('| '+str(i)+' | '+k+' | '+ans.replace('|','/')+' |' for i,(k,ans) in enumerate(q,1));lines+=['','## 검증과 계산 범위','',f"계수 범위는 C2 {base['census']['coefficient_range']}에서 C3 {c['coefficient_range']}로 바뀌었다. 계수 400인 Q 링크를 삭제한 결과이며, 남는 계수·목적·변수 type은 정확히 보존했다. 새 경계는 물리 변수의 관측값이 아니라 C2 affine 정의와 단위별 위치/PCS max-union으로 증명했다. PR160 {read('PR161_REPLAY_PR160_CERTIFICATE_TRANSPORT_AUDIT.json')['rows_checked']:,}개 인증과 PR161 {read('PR161_REPLAY_SUPERCOMPACT_INDEPENDENT_VERIFICATION.json')['all_C1_rows_checked']:,}개 C1행 매핑을 재검증했다.",'','모든 현재 row/column family는 개별 ID 결정 파일과 family ledger에 포함한다. KEEP는 삭제 불가의 완전한 일반 정리를 뜻하지 않는다. 높은 fanout 후보의 비용은 정확한 sparse support union 상한이며 가능한 모든 수치 상쇄를 전수 증명한 값으로 표시하지 않았다. 전역 coupling rank는 structural rank만 보고하고 exact signed-incidence/삼각 정의 블록 외의 미증명 rank 삭제는 하지 않았다. SOC projection은 유한 상·하한의 두 경계 행까지 정확한 비용을 기록했다. 새 polytope, topology recursion, GUB/SOS/indicator, symmetry 후보는 증명이 없거나 비용이 악화되어 유지했다. 실제 C2에서 integer-only로 증명하여 삭제한 행은 0개이며 그런 삭제는 허용하지 않았다.','','Root는 NodeLimit=1의 동일 설정으로 두 모델만 순차 비교한다. root 시간/Work는 native log의 0.01 정밀도 값이며 total Work와 구분한다. MILP도 같은 모든 native parameter(로그 경로 제외), 같은 물리 start, 285초 TimeLimit과 300초 전체 arm 상한을 사용한다. inherited full-domain LB와 안전 조정 native bound를 분리한다. 차이 1e-6 이하의 LB/gap 잡음은 개선으로 선택하지 않는다. time_after_root는 root 직후 native progress의 정수 초와 Runtime을 이용한 근삿값이다. 정확한 root 완료 callback 시각은 수집하지 못했고, Runtime에서 root LP 소요 시간을 단순 차감하면 presolve가 포함되므로 그 값은 별도로 보존했다. 0.5% gap 달성이나 전역 최적 완료를 주장하지 않는다. D-W/B&P/Benders/one-tree B&C/row generation/3600초/parameter sweep은 실행하지 않았다.','','## 재현','', '`python -m v42_ultracompact.forensic C2` → `python -m v42_ultracompact.audit` → `python -m v42_ultracompact.network` → `python -m v42_ultracompact.closure` → `python -m v42_ultracompact.cost_finish` → `python -m v42_ultracompact.verify` → `python -m v42_ultracompact.tests` → `python -m v42_ultracompact.start`.', '', '부모 PR 증명 replay는 원래 verifier의 읽기 전용 입력과 독립 연산을 사용하고 write/table만 새 namespace로 전달했다. 모든 parent artifact는 불변이다. C3B/C3C 동일성은 실제 sparse matrix/data 비교로 확인해 presolve/root/MILP를 중복 실행하지 않았다. `BENCHMARK_ONCE.json`이 있으면 benchmark를 다시 실행하지 않는다.', '', f"실제 4개 native arm 실행 소스는 `{source}`다. `python -m v42_ultracompact.selection`은 이미 수집한 로그/JSON만 읽어 판정과 timing 메타데이터를 재구성하며 optimize를 호출하지 않는다. `python -m v42_ultracompact.report`는 최종 보고서·authority·SHA manifest를 생성한다. 새 scientific 실행 없이 C3를 고정하고 STOP했다."]
    prose('FINAL_REVIEW_KO.md','\n'.join(lines)+'\n')
    missing=[n for n in REQUIRED if not (OUT/n).exists()];assert not missing,missing
    if bench:
        for n in ['ULTRACOMPACT_ROOT_COMPARISON.json','C2_MILP_RESULT.json','C3_MILP_RESULT.json','ULTRACOMPACT_MILP_COMPARISON.json','ULTRACOMPACT_RESOURCE_LEDGER.csv']:assert (OUT/n).exists()
    ledger=list(csv.DictReader((OUT/'EXHAUSTIVE_REDUCTION_LEDGER.csv').open(encoding='utf-8')));assert sum(int(x['tested_count']) for x in ledger if x['kind']=='ROW')==base['census']['rows'];assert sum(int(x['tested_count']) for x in ledger if x['kind']=='COLUMN')==base['census']['columns']
    for p,h in base['frozen_files'].items():assert sha(ROOT/p)==h
    assert v['PASS'] and start['PASS'] and read('STATIC_FIXED_POINT_V2.json')['PASS'];write('VERIFICATION.json',dict(PASS=True,BASE=BASE,required_artifacts_present=True,all_row_families=len(base['census']['row_families']),all_column_families=len(base['census']['column_families']),all_C2_rows=base['census']['rows'],all_C2_columns=base['census']['columns'],parent_frozen_files_unchanged=True,exactness=v['PASS'],fixtures=read('ULTRACOMPACT_FIXTURE_RESULTS.json')['PASS'],adversarial=read('ULTRACOMPACT_ADVERSARIAL_RESULTS.json')['PASS'],start=start['PASS'],true_supported_static_fixed_point=True,benchmark=bench,selected=s['selected'],state=s['state'],source_commit=source))
    label='C3A' if s['selected'] else 'C2';p=OUT if s['selected'] else PARENT;write('ULTRACOMPACT_CURRENT_AUTHORITY_M1.json',dict(PASS=True,selected=s['selected_formulation'],state=s['state'],BASE=BASE,executed_source_commit=source,selected_matrix_SHA256=sha(p/(label+'_A.npz')),selected_data_SHA256=sha(p/(label+'_DATA.npz')),selected_start_SHA256=sha((OUT if s['selected'] else PARENT)/(label+'_VALID_START.npz')),N=4,H=96,P1=True,MIPGap=.005,FeasibilityTol=1e-8,objective_and_integer_feasible_set_preserved=True,algorithm_tournament_executed=False,STOP=True))
    manifest()
def manifest():
    files=sorted([p for p in OUT.iterdir() if p.is_file() and p.name not in ['SHA256_MANIFEST.json','MANIFEST_INDEPENDENT_VERIFICATION.json']]+[p for p in (ROOT/'v42_ultracompact').iterdir() if p.is_file()]);big=[(str(p),p.stat().st_size) for p in files if p.stat().st_size>=100*1024**2];assert not big,('GITHUB_FILE_SIZE_LIMIT',big)
    write('SHA256_MANIFEST.json',dict(PASS=True,algorithm='SHA256',files={str(p.relative_to(ROOT)).replace('\\','/'):sha(p) for p in files},self_excluded=True))
    print('MANIFEST',len(files),'files',flush=True)
if __name__=='__main__':
    import sys
    if 'gate' in sys.argv:gate()
    elif 'manifest' in sys.argv:manifest()
    else:run()
